// HSK1 official vocabulary list (300 words)
const FULL_HSK1 = [
["爱","ài","love"],["吧","ba","(suggestion particle)"],["八","bā","eight"],["爸爸","bàba","dad"],["百","bǎi","hundred"],
["白天","báitiān","daytime"],["半","bàn","half"],["包子","bāozi","steamed bun"],["杯子","bēizi","cup"],["本","běn","(measure word for books)"],
["边","biān","side"],["病","bìng","illness"],["不","bù","not"],["不客气","bú kèqi","you're welcome"],["不要","búyào","don't"],
["菜","cài","dish / vegetable"],["茶","chá","tea"],["超市","chāoshì","supermarket"],["车","chē","car / vehicle"],["吃","chī","eat"],
["穿","chuān","wear"],["出租车","chūzūchē","taxi"],["大","dà","big"],["打电话","dǎ diànhuà","make a phone call"],["大家","dàjiā","everyone"],
["到","dào","arrive / to"],["大学","dàxué","university"],["大学生","dàxuéshēng","college student"],["的","de","(possessive particle)"],["第","dì","(ordinal prefix)"],
["店","diàn","shop"],["点","diǎn","o'clock / point"],["电话","diànhuà","telephone"],["电脑","diànnǎo","computer"],["电视","diànshì","television"],
["电影","diànyǐng","movie"],["电影院","diànyǐngyuàn","cinema"],["弟弟","dìdi","younger brother"],["东西","dōngxi","thing"],["都","dōu","all / both"],
["读","dú","read"],["对不起","duìbuqǐ","sorry"],["多","duō","many / much"],["多少","duōshao","how much / many"],["读书","dúshū","study / read books"],
["二","èr","two"],["儿子","érzi","son"],["饭","fàn","meal / rice"],["饭店","fàndiàn","restaurant / hotel"],["房间","fángjiān","room"],
["非常","fēicháng","extremely"],["飞机","fēijī","airplane"],["分","fēn","minute / cent"],["分钟","fēnzhōng","minute"],["高兴","gāoxìng","happy"],
["个","gè","(general measure word)"],["歌","gē","song"],["哥哥","gēge","older brother"],["给","gěi","give"],["公司","gōngsī","company"],
["工作","gōngzuò","work / job"],["狗","gǒu","dog"],["贵","guì","expensive"],["国","guó","country"],["还","hái","still / also"],
["孩子","háizi","child"],["汉语","Hànyǔ","Chinese language"],["汉字","Hànzì","Chinese character"],["号","hào","number / date"],["好","hǎo","good"],
["好吃","hǎochī","delicious"],["好看","hǎokàn","good-looking"],["好听","hǎotīng","pleasant to hear"],["好玩儿","hǎowánr","fun"],["和","hé","and"],
["喝","hē","drink"],["很","hěn","very"],["后","hòu","after / behind"],["回","huí","return"],["会","huì","can / meeting"],
["火车","huǒchē","train"],["几","jǐ","how many / several"],["家","jiā","home / family"],["见","jiàn","see"],["饺子","jiǎozi","dumplings"],
["家人","jiārén","family members"],["鸡蛋","jīdàn","egg"],["姐姐","jiějie","older sister"],["今年","jīnnián","this year"],["今天","jīntiān","today"],
["九","jiǔ","nine"],["觉得","juéde","feel / think"],["开","kāi","open / drive"],["开车","kāichē","drive a car"],["看","kàn","look / watch"],
["看病","kànbìng","see a doctor"],["看见","kànjiàn","see / catch sight of"],["课","kè","lesson / class"],["可以","kěyǐ","can / may"],["口","kǒu","mouth"],
["块","kuài","(unit of money) / piece"],["来","lái","come"],["老师","lǎoshī","teacher"],["了","le","(completed action particle)"],["冷","lěng","cold"],
["里","lǐ","inside"],["两","liǎng","two (of something)"],["零","líng","zero"],["六","liù","six"],["吗","ma","(question particle)"],
["卖","mài","sell"],["妈妈","māma","mom"],["忙","máng","busy"],["猫","māo","cat"],["没关系","méi guānxi","it's ok / never mind"],
["妹妹","mèimei","younger sister"],["没有","méiyǒu","not have"],["们","men","(plural suffix)"],["米饭","mǐfàn","rice"],["面包","miànbāo","bread"],
["明年","míngnián","next year"],["明天","míngtiān","tomorrow"],["名字","míngzi","name"],["那","nà","that"],["哪","nǎ","which"],
["那边","nàbian","over there"],["哪儿","nǎr","where"],["那个","nàge","that one"],["哪个","nǎge","which one"],["那里","nàli","there"],
["哪里","nǎlǐ","where"],["男","nán","male"],["男朋友","nánpéngyou","boyfriend"],["那儿","nàr","there"],["那些","nàxiē","those"],
["呢","ne","(question particle)"],["能","néng","can / be able to"],["你","nǐ","you"],["年","nián","year"],["你们","nǐmen","you (plural)"],
["您","nín","you (polite)"],["牛奶","niúnǎi","milk"],["女","nǚ","female"],["女儿","nǚ'ér","daughter"],["女朋友","nǚpéngyou","girlfriend"],
["女士","nǚshì","lady / madam"],["朋友","péngyou","friend"],["便宜","piányi","cheap"],["漂亮","piàoliang","pretty"],["苹果","píngguǒ","apple"],
["七","qī","seven"],["前","qián","front / before"],["钱","qián","money"],["千","qiān","thousand"],["起床","qǐchuáng","get up"],
["请","qǐng","please"],["请问","qǐngwèn","excuse me / may I ask"],["去年","qùnián","last year"],["热","rè","hot"],["人","rén","person"],
["认识","rènshi","know / recognize"],["三","sān","three"],["上","shàng","up / above"],["上班","shàngbān","go to work"],["上课","shàngkè","attend class"],
["商店","shāngdiàn","store"],["上学","shàngxué","go to school"],["少","shǎo","few / little"],["谁","shéi","who"],["生病","shēngbìng","get sick"],
["什么","shénme","what"],["生日","shēngrì","birthday"],["十","shí","ten"],["是","shì","to be"],["事","shì","matter / thing"],
["时候","shíhou","time / moment"],["时间","shíjiān","time"],["手机","shǒujī","mobile phone"],["书","shū","book"],["书店","shūdiàn","bookstore"],
["睡","shuì","sleep"],["水果","shuǐguǒ","fruit"],["睡觉","shuìjiào","sleep"],["说","shuō","speak"],["说话","shuōhuà","talk"],
["四","sì","four"],["岁","suì","years old"],["他","tā","he"],["它","tā","it"],["她","tā","she"],
["太","tài","too / extremely"],["她们","tāmen","they (female)"],["它们","tāmen","they (things)"],["他们","tāmen","they"],["天","tiān","day / sky"],
["天气","tiānqì","weather"],["听","tīng","listen"],["听见","tīngjiàn","hear"],["同学","tóngxué","classmate"],["外","wài","outside"],
["外边","wàibian","outside"],["玩","wán","play"],["晚饭","wǎnfàn","dinner"],["晚上","wǎnshang","evening"],["喂","wèi","hello (on phone)"],
["问","wèn","ask"],["问题","wèntí","question / problem"],["我","wǒ","I / me"],["我们","wǒmen","we"],["五","wǔ","five"],
["午饭","wǔfàn","lunch"],["下","xià","down / below"],["下课","xiàkè","finish class"],["想","xiǎng","want / think"],["先生","xiānsheng","Mr. / sir"],
["现在","xiànzài","now"],["小","xiǎo","small"],["小朋友","xiǎopéngyou","child / kid"],["小时","xiǎoshí","hour"],["小学","xiǎoxué","elementary school"],
["小学生","xiǎoxuéshēng","elementary student"],["下午","xiàwǔ","afternoon"],["下雪","xiàxuě","snow (verb)"],["下雨","xiàyǔ","rain (verb)"],["写","xiě","write"],
["些","xiē","some"],["谢谢","xièxie","thank you"],["喜欢","xǐhuan","like"],["新","xīn","new"],["星期","xīngqī","week"],
["星期天","xīngqītiān","Sunday"],["休息","xiūxi","rest"],["学生","xuésheng","student"],["学习","xuéxí","study"],["学校","xuéxiào","school"],
["雪","xuě","snow"],["眼睛","yǎnjing","eyes"],["羊肉","yángròu","mutton"],["要","yào","want / need"],["也","yě","also"],
["一","yī","one"],["一半","yíbàn","half"],["一点儿","yìdiǎnr","a little"],["衣服","yīfu","clothes"],["医生","yīshēng","doctor"],
["一下","yíxià","(briefly / a bit)"],["一些","yìxiē","some"],["医院","yīyuàn","hospital"],["椅子","yǐzi","chair"],["有","yǒu","have"],
["有的","yǒude","some"],["有点儿","yǒudiǎnr","a bit"],["雨","yǔ","rain"],["月","yuè","month"],["在","zài","at / in"],
["再","zài","again"],["再见","zàijiàn","goodbye"],["早","zǎo","early / morning"],["早饭","zǎofàn","breakfast"],["早上","zǎoshang","morning"],
["怎么","zěnme","how"],["怎么样","zěnmeyàng","how about"],["找","zhǎo","look for"],["这","zhè","this"],["这边","zhèbian","this side"],
["这个","zhège","this one"],["这里","zhèli","here"],["真","zhēn","really"],["正在","zhèngzài","currently (doing)"],["这儿","zhèr","here"],
["这些","zhèxiē","these"],["只","zhǐ","only"],["知道","zhīdào","know"],["中国","zhōngguó","China"],["中文","zhōngwén","Chinese (language)"],
["中午","zhōngwǔ","noon"],["中学","zhōngxué","middle school"],["中学生","zhōngxuéshēng","middle school student"],["住","zhù","live / reside"],["桌子","zhuōzi","table"],
["字","zì","character / word"],["昨天","zuótiān","yesterday"],["坐","zuò","sit"],["做","zuò","do / make"],["做饭","zuòfàn","cook"]
];

// Easy Steps to Chinese 1 (ES1) vocabulary list, transcribed from the textbook glossary
const FULL_ES1 = [
["阿","ā","a prefix (added to a title)"],["阿姨","āyí","aunt"],["矮","ǎi","short (in height)"],["爱","ài","like; love"],["爱好","àihào","hobby"],
["八","bā","eight"],["爸爸","bàba","dad; father"],["白","bái","white"],["白色","báisè","white"],["班","bān","shift; duty"],
["半","bàn","half"],["北京","Běijīng","Beijing"],["鼻","bí","nose"],["鼻子","bízi","nose"],["不见","bújiàn","disappear; be missing"],
["不","bù","no; not"],["步","bù","step"],["差","chà","fall short of"],["长","cháng","long"],["长裤","chángkù","trousers"],
["常","cháng","often; ordinary"],["常常","chángcháng","often"],["唱","chàng","sing"],["唱歌","chàng gē","sing"],["车","chē","vehicle"],
["衬","chèn","liner"],["衬衫","chènshān","shirt"],["橙","chéng","orange"],["橙色","chéngsè","orange"],["吃","chī","eat"],
["宠","chǒng","spoil"],["宠物","chǒngwù","pet"],["出","chū","go or come out"],["出生","chūshēng","be born"],["穿","chuān","wear"],
["床","chuáng","bed"],["打","dǎ","play"],["打篮球","dǎ lánqiú","play basketball"],["大","dà","big"],["大","dà","(of age) old"],
["大学","dàxué","university"],["大学生","dàxuéshēng","university student"],["大月","dàyuè","a solar month of 31 days"],["但","dàn","but"],["但是","dànshì","but"],
["的","de","'s; of"],["得","de","(a particle)"],["等","děng","etc."],["等等","děngděng","etc."],["地","dì","land; ground"],
["地铁","dìtiě","underground"],["弟弟","dì(di)","younger brother"],["点","diǎn","o'clock"],["电","diàn","electricity"],["电话","diànhuà","telephone"],
["动","dòng","move"],["动物","dòngwù","animal"],["都","dōu","both; all"],["独","dú","only"],["独生女","dúshēngnǚ","only daughter"],
["独生子","dúshēngzǐ","only son"],["短","duǎn","short (in length)"],["短裤","duǎnkù","shorts"],["多","duō","many; much"],["多大","duō dà","how old"],
["多少","duōshao","how many; how much"],["儿","ér","child"],["儿","ér","(a suffix)"],["耳","ěr","ear"],["耳朵","ěrduo","ear"],
["二","èr","two"],["发","fà","hair"],["饭","fàn","meal"],["放","fàng","let out"],["放学","fàngxué","school is over"],
["非","fēi","not"],["非常","fēicháng","extremely"],["分","fēn","minute"],["粉","fěn","pink"],["粉色","fěnsè","pink"],
["服","fú","clothes"],["高","gāo","tall"],["哥哥","gē(ge)","older brother"],["歌","gē","song"],["个","gè","a measure word (for a noun with no particular measure word)"],
["个子","gèzi","height; stature"],["跟","gēn","with"],["工","gōng","work"],["工作","gōngzuò","work"],["公","gōng","public"],
["公共","gōnggòng","public"],["公共汽车","gōnggòng qìchē","public bus"],["共","gòng","common"],["狗","gǒu","dog"],["国","guó","country"],
["果","guǒ","fruit"],["还","hái","also; in addition"],["孩","hái","child"],["行","háng","business firm"],["好","hǎo","good"],
["好","hǎo","used as a polite formula"],["好","hǎo","OK"],["好看","hǎokàn","good-looking; pretty"],["好朋友","hǎo péngyou","good friend"],["好玩儿","hǎowánr","amusing; fun"],
["号","hào","date of a month"],["号","hào","ordinal number"],["号码","hàomǎ","number"],["好","hào","be fond of"],["喝","hē","drink"],
["和","hé","and"],["黑","hēi","black"],["黑色","hēisè","black"],["很","hěn","very"],["很多","hěn duō","a lot of"],
["红","hóng","red"],["红色","hóngsè","red"],["话","huà","word"],["欢","huān","happy"],["黄","huáng","yellow"],
["黄色","huángsè","yellow"],["灰","huī","grey"],["灰色","huīsè","grey"],["会","huì","moment"],["会","huì","can"],
["会儿","huìr","a little while"],["混","hùn","mix"],["混血儿","hùnxuè'ér","person of mixed blood"],["机","jī","machine"],["机器","jīqì","machine"],
["机器人","jīqìrén","robot"],["级","jí","grade"],["几","jǐ","how many"],["家","jiā","family; home"],["家","jiā","expert"],
["见","jiàn","meet with"],["脚","jiǎo","foot"],["叫","jiào","name; call"],["觉","jiào","sleep"],["姐姐","jiě(jie)","older sister"],
["姐妹","jiěmèi","sisters"],["今","jīn","current; present"],["今年","jīnnián","this year"],["今天","jīntiān","today"],["进","jìn","come in"],
["经","jīng","manage"],["经理","jīnglǐ","manager"],["睛","jīng","eyeball"],["九","jiǔ","nine"],["开","kāi","drive"],
["开车","kāichē","drive"],["看","kàn","look; see"],["看","kàn","read"],["看见","kànjiàn","see"],["看书","kàn shū","read a book"],
["可","kě","be worth (doing)"],["可爱","kě'ài","cute; lovely"],["刻","kè","a quarter (of an hour)"],["课","kè","lesson; class"],["口","kǒu","a measure word (for family members)"],
["裤","kù","trousers"],["裤子","kùzi","trousers"],["快","kuài","happy"],["快乐","kuàilè","happy"],["来","lái","come"],
["蓝","lán","blue"],["蓝色","lánsè","blue"],["篮","lán","basket"],["篮球","lánqiú","basketball"],["老","lǎo","(a prefix)"],
["老师","lǎoshī","teacher"],["乐","lè","happy"],["了","le","(a particle)"],["理","lǐ","manage"],["脸","liǎn","face"],
["两","liǎng","two"],["〇","líng","zero"],["零","líng","zero"],["六","liù","six"],["路","lù","road; street"],
["律","lǜ","law"],["律师","lǜshī","lawyer"],["绿","lǜ","green"],["绿色","lǜsè","green"],["妈妈","mā(ma)","mum; mother"],
["马","Mǎ","a surname"],["码","mǎ","number"],["吗","ma","(a particle)"],["忙","máng","busy"],["猫","māo","cat"],
["毛","máo","wool"],["毛","máo","hair; feather"],["毛衣","máoyī","sweater"],["没","méi","not have"],["没有","méiyǒu","not have"],
["每","měi","every"],["每天","měi tiān","every day"],["美国","Měiguó","America"],["美国人","Měiguórén","American (people)"],["妹妹","mèi(mei)","younger sister"],
["们","men","a suffix for plurals"],["秘","mì","secret"],["秘书","mìshū","secretary"],["名","míng","name"],["名字","míngzi","name"],
["明","míng","immediately following in time"],["明天","míngtiān","tomorrow"],["哪","nǎ","which; what"],["哪儿","nǎr","where"],["哪些","nǎxiē","which; what"],
["那","nà","that"],["那儿","nàr","there"],["那些","nàxiē","those"],["呢","ne","(a particle)"],["你","nǐ","you"],
["你们","nǐmen","you (plural)"],["年","nián","year"],["年级","niánjí","grade"],["鸟","niǎo","bird"],["您","nín","you (respectful)"],
["牛","niú","cow"],["牛仔","niúzǎi","cowboy"],["牛仔裤","niúzǎikù","jeans"],["女","nǚ","female; daughter"],["女孩儿","nǚhái'r","girl"],
["胖","pàng","fat; plump"],["跑","pǎo","run"],["跑步","pǎobù","run; jog"],["朋","péng","friend"],["朋友","péngyou","friend"],
["皮","pí","leather"],["皮鞋","píxié","leather shoes"],["七","qī","seven"],["期","qī","a period of time"],["骑","qí","ride"],
["起","qǐ","get up"],["起床","qǐchuáng","get up"],["汽","qì","vapour; steam"],["汽车","qìchē","automobile"],["器","qì","instrument; tool"],
["请","qǐng","please"],["球","qiú","ball"],["去","qù","go"],["裙","qún","skirt"],["裙子","qúnzi","skirt"],
["人","rén","person"],["日","rì","day"],["三","sān","three"],["三十一天","sānshíyī tiān","thirty-one days"],["色","sè","colour"],
["衫","shān","top (clothes)"],["商","shāng","business"],["商人","shāngrén","business person"],["上","shàng","previous"],["上","shàng","go"],
["上班","shàngbān","go to work"],["上海","Shànghǎi","Shanghai"],["上课","shàngkè","attend class"],["上午","shàngwǔ","late morning (usually 09:00–12:00)"],["上学","shàngxué","go to school"],
["上","shang","(a suffix)"],["上","shang","used after a noun to indicate the surface of an object"],["少","shǎo","few; little"],["谁","shéi","who"],["身","shēn","body"],
["身上","shēnshang","on one's body"],["身体","shēntǐ","body"],["什么","shénme","what"],["生","shēng","be born"],["生","shēng","student"],
["生","shēng","(a suffix of certain nouns referring to people)"],["生日","shēngrì","birthday"],["师","shī","teacher; someone with a specialized skill"],["十","shí","ten"],["是","shì","be"],
["室","shì","room"],["手","shǒu","hand"],["手机","shǒujī","mobile phone"],["瘦","shòu","thin; slim"],["书","shū","document; book"],
["水","shuǐ","water"],["水果","shuǐguǒ","fruit"],["睡","shuì","sleep"],["睡觉","shuìjiào","sleep"],["四","sì","four"],
["岁","suì","year (of age)"],["他","tā","he; him"],["他们","tāmen","they; them"],["它","tā","it"],["它们","tāmen","they; them (non-human plural)"],
["她","tā","she; her"],["她们","tāmen","they; them (female)"],["套","tào","cover"],["踢","tī","kick"],["踢足球","tī zúqiú","play football"],
["体","tǐ","body"],["天","tiān","day"],["跳","tiào","jump"],["跳舞","tiàowǔ","dance"],["铁","tiě","iron"],
["听","tīng","listen"],["听音乐","tīng yīnyuè","listen to music"],["同","tóng","same"],["同学","tóngxué","schoolmate"],["头","tóu","head"],
["头发","tóufa","hair"],["腿","tuǐ","leg"],["T恤","T xù","T-shirt"],["外","wài","outside"],["外套","wàitào","jacket; coat"],
["玩","wán","play"],["玩儿","wánr","play"],["晚","wǎn","evening"],["晚饭","wǎnfàn","dinner"],["晚上","wǎnshang","evening; night (usually 18:00–24:00)"],
["王","Wáng","a surname"],["尾","wěi","tail"],["尾巴","wěiba","tail"],["我","wǒ","I; me"],["我们","wǒmen","we; us"],
["五","wǔ","five"],["午","wǔ","noon"],["午饭","wǔfàn","lunch"],["舞","wǔ","dance"],["物","wù","creature"],
["喜","xǐ","be fond of"],["喜欢","xǐhuan","like"],["下","xià","latter"],["下午","xiàwǔ","afternoon (usually 13:00–18:00)"],["现","xiàn","present; current"],
["现在","xiànzài","now"],["小","xiǎo","small"],["小学","xiǎoxué","primary school"],["小学生","xiǎoxuéshēng","primary school student"],["小月","xiǎoyuè","a solar month of 30 days"],
["校","xiào","school"],["校车","xiàochē","school bus"],["校服","xiàofú","school uniform"],["些","xiē","some; a few"],["鞋","xié","shoes"],
["谢","xiè","thank"],["谢谢","xièxie","thanks"],["星","xīng","star"],["星期","xīngqī","week"],["星期日","xīngqīrì","Sunday"],
["星期天","xīngqītiān","Sunday"],["星期一","xīngqīyī","Monday"],["行","xíng","go"],["姓","xìng","surname"],["兄","xiōng","older brother"],
["兄弟","xiōngdì","brothers"],["学","xué","school; study"],["学生","xuéshēng","student"],["学校","xuéxiào","school"],["血","xuè","blood"],
["颜","yán","colour"],["颜色","yánsè","colour"],["眼","yǎn","eye"],["眼睛","yǎnjing","eye"],["养","yǎng","raise; keep"],
["样","yàng","appearance"],["也","yě","also"],["一","yī","one"],["一月","yīyuè","January"],["衣","yī","clothes"],
["衣服","yīfu","clothes"],["医","yī","doctor (of medicine)"],["医生","yīshēng","doctor"],["一个星期","yí gè xīngqī","one week"],["一个月","yí gè yuè","one month"],
["一会儿","yíhuìr","a little while"],["姨","yí","aunt"],["一家人","yì jiā rén","one family"],["一年","yì nián","one year"],["一起","yìqǐ","together"],
["音","yīn","sound"],["音乐","yīnyuè","music"],["银","yín","related to money"],["银行","yínháng","bank"],["银行家","yínhángjiā","banker"],
["英国","Yīngguó","Britain"],["英国人","Yīngguórén","British"],["泳","yǒng","swim"],["游","yóu","swim"],["游泳","yóuyǒng","swim"],
["友","yǒu","friend"],["有","yǒu","have"],["圆","yuán","round"],["月","yuè","month"],["乐","yuè","music"],
["运","yùn","move"],["运动","yùndòng","sports"],["仔","zǎi","young man"],["再","zài","again"],["再见","zàijiàn","good-bye; see you again"],
["在","zài","in; on; at"],["早","zǎo","morning"],["早饭","zǎofàn","breakfast"],["早上","zǎoshang","early morning (usually 05:00–09:00)"],["怎么","zěnme","how"],
["长","zhǎng","grow"],["这","zhè","this"],["这儿","zhèr","here"],["这些","zhèxiē","these"],["真","zhēn","really"],
["只","zhī","a measure word (for small animals)"],["中","zhōng","middle"],["中国","Zhōngguó","China"],["中国人","Zhōngguórén","Chinese (people)"],["中午","zhōngwǔ","noon (usually 12:00–13:00)"],
["中学","zhōngxué","secondary school"],["中学生","zhōngxuéshēng","secondary school student"],["自","zì","self; oneself"],["自行车","zìxíngchē","bicycle"],["字","zì","name"],
["子","zi","(a suffix)"],["棕","zōng","brown"],["棕色","zōngsè","brown"],["走","zǒu","walk"],["走路","zǒulù","walk"],
["足","zú","foot"],["足球","zúqiú","football"],["嘴","zuǐ","mouth"],["嘴巴","zuǐba","mouth"],["昨","zuó","yesterday"],
["昨天","zuótiān","yesterday"],["作","zuò","do"],["坐","zuò","sit"],["坐","zuò","travel by"],["坐地铁","zuò dìtiě","take the underground"],
["做","zuò","do"]
];

// HSK 3.0 Level 2 official vocabulary list (204 words)
const FULL_HSK2 = [
["啊","a","ah (particle)"],["爱好","àihào","hobby"],["白色","báisè","white"],["班","bān","class/shift"],["帮","bāng","help"],["帮忙","bāngmáng","help; do a favor"],["包","bāo","bag"],["本子","běnzi","notebook"],["比","bǐ","compare; than"],["笔","bǐ","pen"],["别","bié","don't"],["不错","búcuò","pretty good"],
["不好意思","bù hǎoyìsi","embarrassed; sorry"],["长","cháng","long"],["车站","chēzhàn","station"],["出","chū","go out"],["床","chuáng","bed"],["出国","chūguó","go abroad"],["出来","chūlái","come out"],["出门","chūmén","go out"],["出去","chūqù","go out"],
["词","cí","word"],["次","cì","time (occurrence)"],["从","cóng","from"],["从小","cóngxiǎo","since childhood"],["错","cuò","wrong"],["打","dǎ","hit; play"],["打车","dǎchē","take a taxi"],["打开","dǎkāi","open"],["但","dàn","but"],["但是","dànshì","but"],["得","de","(complement particle)"],["地","de","(adverbial particle)"],["等","děng","wait"],
["点","diǎn","o'clock; order"],["地铁","dìtiě","subway"],["动","dòng","move"],["懂","dǒng","understand"],["多","duō","many; much"],["饭馆","fànguǎn","restaurant"],["飞","fēi","fly"],["高","gāo","tall"],["告诉","gàosu","tell"],["高中","gāozhōng","high school"],["给","gěi","give"],["跟","gēn","with; follow"],
["个子","gèzi","height; stature"],["公交车","gōngjiāochē","bus"],["过","guò","pass; cross"],["过","guo","(past experience particle)"],["过来","guòlái","come over"],["过年","guònián","celebrate new year"],["过去","guòqù","past; go over"],["还是","háishi","or; still"],["好","hǎo","good"],["黑色","hēisè","black"],
["红茶","hóngchá","black tea"],["红色","hóngsè","red"],["后面","hòumiàn","behind"],["画","huà","draw; painting"],["花","huā","flower"],["花","huā","spend (money/time)"],["坏","huài","bad; broken"],["回来","huílái","come back"],["回去","huíqù","go back"],["间","jiān","room; measure word"],["教","jiāo","teach"],
["教室","jiàoshì","classroom"],["机场","jīchǎng","airport"],["记得","jìde","remember"],["介绍","jièshào","introduce"],["近","jìn","near"],["进","jìn","enter"],["经常","jīngcháng","often"],["进来","jìnlái","come in"],["进去","jìnqù","go in"],
["机票","jīpiào","plane ticket"],["就","jiù","just; then"],["酒店","jiǔdiàn","hotel"],["咖啡","kāfēi","coffee"],["开始","kāishǐ","start"],["开学","kāixué","start school"],["考","kǎo","test (verb)"],["考试","kǎoshì","exam"],["可能","kěnéng","maybe; possible"],["快","kuài","fast"],
["快乐","kuàilè","happy"],["快要","kuàiyào","about to"],["裤子","kùzi","pants"],["篮球","lánqiú","basketball"],["累","lèi","tired"],["离","lí","from; away from"],["里面","lǐmiàn","inside"],["楼","lóu","building; floor"],["路","lù","road"],["绿茶","lǜchá","green tea"],["绿色","lǜsè","green"],
["路上","lùshang","on the way"],["旅游","lǚyóu","travel"],["慢","màn","slow"],["每","měi","every"],["没意思","méi yìsi","boring"],["门","mén","door"],["门口","ménkǒu","doorway"],["门票","ménpiào","entrance ticket"],["面","miàn","side; surface"],["名","míng","name"],["拿","ná","take; hold"],
["那","nà","that"],["奶茶","nǎichá","milk tea"],["奶奶","nǎinai","grandmother (paternal)"],["那么","nàme","so; like that"],["男孩儿","nánháir","boy"],["那样","nàyàng","like that"],["鸟","niǎo","bird"],["女孩儿","nǚháir","girl"],["旁边","pángbiān","beside"],["跑","pǎo","run"],
["跑步","pǎobù","jog"],["票","piào","ticket"],["前面","qiánmiàn","in front"],["起来","qǐlái","get up; stand up"],["晴","qíng","sunny; clear"],["球","qiú","ball"],["妻子","qīzi","wife"],["让","ràng","let; allow"],["肉","ròu","meat"],["商场","shāngchǎng","shopping mall"],
["上来","shànglái","come up"],["上面","shàngmiàn","above; on top"],["上去","shàngqù","go up"],["上网","shàngwǎng","go online"],["生日","shēngrì","birthday"],["身体","shēntǐ","body; health"],["时","shí","time"],
["事情","shìqing","matter; thing"],["手","shǒu","hand"],["手表","shǒubiǎo","watch (wrist)"],["书包","shūbāo","schoolbag"],["舒服","shūfu","comfortable"],["送","sòng","give; send; deliver"],["虽然","suīrán","although"],["所以","suǒyǐ","so; therefore"],["疼","téng","hurt; painful"],["题","tí","question; problem"],
["踢","tī","kick"],["条","tiáo","(measure word, long thin things)"],["跳舞","tiàowǔ","dance"],["头","tóu","head"],["外国","wàiguó","foreign country"],["外面","wàimiàn","outside"],["完","wán","finish"],["万","wàn","ten thousand"],["忘","wàng","forget"],["往","wǎng","toward"],["网上","wǎngshàng","online"],
["位","wèi","(polite measure word for people)"],["为什么","wèishénme","why"],["洗","xǐ","wash"],["下来","xiàlái","come down"],["下面","xiàmiàn","below; next"],["笑","xiào","laugh; smile"],["小孩儿","xiǎoháir","child"],["小时候","xiǎoshíhou","childhood"],
["下去","xiàqù","go down"],["姓","xìng","surname"],["姓名","xìngmíng","full name"],["洗手间","xǐshǒujiān","restroom"],["希望","xīwàng","hope"],["眼睛","yǎnjing","eyes"],["颜色","yánsè","color"],["药","yào","medicine"],
["药店","yàodiàn","pharmacy"],["爷爷","yéye","grandfather (paternal)"],["一会儿","yíhuìr","a moment; a while"],["已经","yǐjīng","already"],["阴","yīn","overcast; cloudy"],["因为","yīnwèi","because"],["一起","yìqǐ","together"],["意思","yìsi","meaning"],["游","yóu","swim"],["右","yòu","right (direction)"],
["右边","yòubian","right side"],["有时","yǒushí","sometimes"],["有意思","yǒu yìsi","interesting"],["游泳","yóuyǒng","swim"],["鱼","yú","fish"],["远","yuǎn","far"],["运动","yùndòng","sports; exercise"],["站","zhàn","stand; station"],
["丈夫","zhàngfu","husband"],["着","zhe","(continuous action particle)"],["这么","zhème","so; like this"],["正","zhèng","exactly; just"],["这样","zhèyàng","like this"],["周","zhōu","week"],["准备","zhǔnbèi","prepare"],["自己","zìjǐ","oneself"],["走","zǒu","walk"],["走路","zǒulù","walk"],["最","zuì","most"],
["左","zuǒ","left"],["左边","zuǒbian","left side"],["足球","zúqiú","football; soccer"]
];
