// HSK1 official vocabulary list (300 words)
const FULL_HSK1 = [
["爱","ài","love"],["吧","ba","(suggestion particle)"],["八","bā","eight"],["爸爸","bàba","dad"],["百","bǎi","hundred"],
["白天","báitiān","daytime"],["半","bàn","half"],["包子","bāozi","steamed bun"],["杯子","bēizi","cup"],["本","běn","(measure word for books)"],
["边","biān","side"],["病","bìng","illness"],["不","bù","not"],["不客气","bú kèqi","you're welcome"],["不要","búyào","don't"],
["菜","cài","dish / vegetable"],["茶","chá","tea"],["超市","chāoshì","supermarket"],["车","chē","car / vehicle"],["吃","chī","eat"],
["穿","chuān","wear"],["出租车","chūzūchē","taxi"],["大","dà","big"],["打电话","dǎ diànhuà","make a phone call"],["大家","dàjiā","everyone"],
["到","dào","arrive / to"],["大学","dàxué","university"],["大学生","dàxuéshēng","college student"],["的","de","(possessive particle)"],["第","dì","(ordinal prefix)"],
["店","diàn","shop"],["点","diǎn","o'clock / point"],["电话","diànhuà","telephone"],["电脑","diànnǎo","computer"],["电视","diànshì","television"],
["电影","diànyǐng","movie"],["电影院","diànyǐngyuàn","cinema"],["弟弟","dìdi","younger brother"],["东西","dōngxi","thing"],["都","dōu","all / both"],
["读","dú","read"],["对不起","duìbuqǐ","sorry"],["多","duō","many / much"],["多少","duōshao","how much / many"],["读书","dúshū","study / read books"],
["二","èr","two"],["儿子","érzi","son"],["饭","fàn","meal / rice"],["饭店","fàndiàn","restaurant / hotel"],["房间","fángjiān","room"],
["非常","fēicháng","extremely"],["飞机","fēijī","airplane"],["分","fēn","minute / cent"],["分钟","fēnzhōng","minute"],["高兴","gāoxìng","happy"],
["个","gè","(general measure word)"],["歌","gē","song"],["哥哥","gēge","older brother"],["给","gěi","give"],["公司","gōngsī","company"],
["工作","gōngzuò","work / job"],["狗","gǒu","dog"],["贵","guì","expensive"],["国","guó","country"],["还","hái","still / also"],
["孩子","háizi","child"],["汉语","Hànyǔ","Chinese language"],["汉字","Hànzì","Chinese character"],["号","hào","number / date"],["好","hǎo","good"],
["好吃","hǎochī","delicious"],["好看","hǎokàn","good-looking"],["好听","hǎotīng","pleasant to hear"],["好玩儿","hǎowánr","fun"],["和","hé","and"],
["喝","hē","drink"],["很","hěn","very"],["后","hòu","after / behind"],["回","huí","return"],["会","huì","can / meeting"],
["火车","huǒchē","train"],["几","jǐ","how many / several"],["家","jiā","home / family"],["见","jiàn","see"],["饺子","jiǎozi","dumplings"],
["家人","jiārén","family members"],["鸡蛋","jīdàn","egg"],["姐姐","jiějie","older sister"],["今年","jīnnián","this year"],["今天","jīntiān","today"],
["九","jiǔ","nine"],["觉得","juéde","feel / think"],["开","kāi","open / drive"],["开车","kāichē","drive a car"],["看","kàn","look / watch"],
["看病","kànbìng","see a doctor"],["看见","kànjiàn","see / catch sight of"],["课","kè","lesson / class"],["可以","kěyǐ","can / may"],["口","kǒu","mouth"],
["块","kuài","(unit of money) / piece"],["来","lái","come"],["老师","lǎoshī","teacher"],["了","le","(completed action particle)"],["冷","lěng","cold"],
["里","lǐ","inside"],["两","liǎng","two (of something)"],["零","líng","zero"],["六","liù","six"],["吗","ma","(question particle)"],
["卖","mài","sell"],["妈妈","māma","mom"],["忙","máng","busy"],["猫","māo","cat"],["没关系","méi guānxi","it's ok / never mind"],
["妹妹","mèimei","younger sister"],["没有","méiyǒu","not have"],["们","men","(plural suffix)"],["米饭","mǐfàn","rice"],["面包","miànbāo","bread"],
["明年","míngnián","next year"],["明天","míngtiān","tomorrow"],["名字","míngzi","name"],["那","nà","that"],["哪","nǎ","which"],
["那边","nàbian","over there"],["哪儿","nǎr","where"],["那个","nàge","that one"],["哪个","nǎge","which one"],["那里","nàli","there"],
["哪里","nǎlǐ","where"],["男","nán","male"],["男朋友","nánpéngyou","boyfriend"],["那儿","nàr","there"],["那些","nàxiē","those"],
["呢","ne","(question particle)"],["能","néng","can / be able to"],["你","nǐ","you"],["年","nián","year"],["你们","nǐmen","you (plural)"],
["您","nín","you (polite)"],["牛奶","niúnǎi","milk"],["女","nǚ","female"],["女儿","nǚ'ér","daughter"],["女朋友","nǚpéngyou","girlfriend"],
["女士","nǚshì","lady / madam"],["朋友","péngyou","friend"],["便宜","piányi","cheap"],["漂亮","piàoliang","pretty"],["苹果","píngguǒ","apple"],
["七","qī","seven"],["前","qián","front / before"],["钱","qián","money"],["千","qiān","thousand"],["起床","qǐchuáng","get up"],
["请","qǐng","please"],["请问","qǐngwèn","excuse me / may I ask"],["去年","qùnián","last year"],["热","rè","hot"],["人","rén","person"],
["认识","rènshi","know / recognize"],["三","sān","three"],["上","shàng","up / above"],["上班","shàngbān","go to work"],["上课","shàngkè","attend class"],
["商店","shāngdiàn","store"],["上学","shàngxué","go to school"],["少","shǎo","few / little"],["谁","shéi","who"],["生病","shēngbìng","get sick"],
["什么","shénme","what"],["生日","shēngrì","birthday"],["十","shí","ten"],["是","shì","to be"],["事","shì","matter / thing"],
["时候","shíhou","time / moment"],["时间","shíjiān","time"],["手机","shǒujī","mobile phone"],["书","shū","book"],["书店","shūdiàn","bookstore"],
["睡","shuì","sleep"],["水果","shuǐguǒ","fruit"],["睡觉","shuìjiào","sleep"],["说","shuō","speak"],["说话","shuōhuà","talk"],
["四","sì","four"],["岁","suì","years old"],["他","tā","he"],["它","tā","it"],["她","tā","she"],
["太","tài","too / extremely"],["她们","tāmen","they (female)"],["它们","tāmen","they (things)"],["他们","tāmen","they"],["天","tiān","day / sky"],
["天气","tiānqì","weather"],["听","tīng","listen"],["听见","tīngjiàn","hear"],["同学","tóngxué","classmate"],["外","wài","outside"],
["外边","wàibian","outside"],["玩","wán","play"],["晚饭","wǎnfàn","dinner"],["晚上","wǎnshang","evening"],["喂","wèi","hello (on phone)"],
["问","wèn","ask"],["问题","wèntí","question / problem"],["我","wǒ","I / me"],["我们","wǒmen","we"],["五","wǔ","five"],
["午饭","wǔfàn","lunch"],["下","xià","down / below"],["下课","xiàkè","finish class"],["想","xiǎng","want / think"],["先生","xiānsheng","Mr. / sir"],
["现在","xiànzài","now"],["小","xiǎo","small"],["小朋友","xiǎopéngyou","child / kid"],["小时","xiǎoshí","hour"],["小学","xiǎoxué","elementary school"],
["小学生","xiǎoxuéshēng","elementary student"],["下午","xiàwǔ","afternoon"],["下雪","xiàxuě","snow (verb)"],["下雨","xiàyǔ","rain (verb)"],["写","xiě","write"],
["些","xiē","some"],["谢谢","xièxie","thank you"],["喜欢","xǐhuan","like"],["新","xīn","new"],["星期","xīngqī","week"],
["星期天","xīngqītiān","Sunday"],["休息","xiūxi","rest"],["学生","xuésheng","student"],["学习","xuéxí","study"],["学校","xuéxiào","school"],
["雪","xuě","snow"],["眼睛","yǎnjing","eyes"],["羊肉","yángròu","mutton"],["要","yào","want / need"],["也","yě","also"],
["一","yī","one"],["一半","yíbàn","half"],["一点儿","yìdiǎnr","a little"],["衣服","yīfu","clothes"],["医生","yīshēng","doctor"],
["一下","yíxià","(briefly / a bit)"],["一些","yìxiē","some"],["医院","yīyuàn","hospital"],["椅子","yǐzi","chair"],["有","yǒu","have"],
["有的","yǒude","some"],["有点儿","yǒudiǎnr","a bit"],["雨","yǔ","rain"],["月","yuè","month"],["在","zài","at / in"],
["再","zài","again"],["再见","zàijiàn","goodbye"],["早","zǎo","early / morning"],["早饭","zǎofàn","breakfast"],["早上","zǎoshang","morning"],
["怎么","zěnme","how"],["怎么样","zěnmeyàng","how about"],["找","zhǎo","look for"],["这","zhè","this"],["这边","zhèbian","this side"],
["这个","zhège","this one"],["这里","zhèli","here"],["真","zhēn","really"],["正在","zhèngzài","currently (doing)"],["这儿","zhèr","here"],
["这些","zhèxiē","these"],["只","zhǐ","only"],["知道","zhīdào","know"],["中国","zhōngguó","China"],["中文","zhōngwén","Chinese (language)"],
["中午","zhōngwǔ","noon"],["中学","zhōngxué","middle school"],["中学生","zhōngxuéshēng","middle school student"],["住","zhù","live / reside"],["桌子","zhuōzi","table"],
["字","zì","character / word"],["昨天","zuótiān","yesterday"],["坐","zuò","sit"],["做","zuò","do / make"],["做饭","zuòfàn","cook"],
["杯","bēi","cup / glass (measure word)"],["唱","chàng","sing"],["对","duì","correct / towards"],["件","jiàn","(measure word for clothes/items)"],["叫","jiào","be called / call"],
["没","méi","not (have)"],["没事","méishì","it's nothing / no big deal"],["面条儿","miàntiáor","noodles"],["你好","nǐ hǎo","hello"],["前边","qiánbian","front side"],
["去","qù","go"],["日","rì","day / sun"],["上午","shàngwǔ","morning"],["水","shuǐ","water"],["晚","wǎn","late / evening"],
["下班","xiàbān","get off work"],["星期日","xīngqīrì","Sunday"],["学","xué","learn / study"]
];

// Easy Steps to Chinese 1 (ES1) vocabulary list, transcribed from the textbook glossary
const FULL_ES1 = [
["阿","ā","a prefix (added to a title)"],["阿姨","āyí","aunt"],["矮","ǎi","short (in height)"],["爱","ài","like; love"],["爱好","àihào","hobby"],
["八","bā","eight"],["爸爸","bàba","dad; father"],["白","bái","white"],["白色","báisè","white"],["班","bān","shift; duty"],
["半","bàn","half"],["北京","Běijīng","Beijing"],["鼻","bí","nose"],["鼻子","bízi","nose"],["不见","bújiàn","disappear; be missing"],
["不","bù","no; not"],["步","bù","step"],["差","chà","fall short of"],["长","cháng","long"],["长裤","chángkù","trousers"],
["常","cháng","often; ordinary"],["常常","chángcháng","often"],["唱","chàng","sing"],["唱歌","chàng gē","sing"],["车","chē","vehicle"],
["衬","chèn","liner"],["衬衫","chènshān","shirt"],["橙","chéng","orange"],["橙色","chéngsè","orange"],["吃","chī","eat"],
["宠","chǒng","spoil"],["宠物","chǒngwù","pet"],["出","chū","go or come out"],["出生","chūshēng","be born"],["穿","chuān","wear"],
["床","chuáng","bed"],["打","dǎ","play"],["打篮球","dǎ lánqiú","play basketball"],["大","dà","big"],["大","dà","(of age) old"],
["大学","dàxué","university"],["大学生","dàxuéshēng","university student"],["大月","dàyuè","a solar month of 31 days"],["但","dàn","but"],["但是","dànshì","but"],
["的","de","'s; of"],["得","de","(a particle)"],["等","děng","etc."],["等等","děngděng","etc."],["地","dì","land; ground"],
["地铁","dìtiě","underground"],["弟弟","dì(di)","younger brother"],["点","diǎn","o'clock"],["电","diàn","electricity"],["电话","diànhuà","telephone"],
["动","dòng","move"],["动物","dòngwù","animal"],["都","dōu","both; all"],["独","dú","only"],["独生女","dúshēngnǚ","only daughter"],
["独生子","dúshēngzǐ","only son"],["短","duǎn","short (in length)"],["短裤","duǎnkù","shorts"],["多","duō","many; much"],["多大","duō dà","how old"],
["多少","duōshao","how many; how much"],["儿","ér","child"],["儿","ér","(a suffix)"],["耳","ěr","ear"],["耳朵","ěrduo","ear"],
["二","èr","two"],["发","fà","hair"],["饭","fàn","meal"],["放","fàng","let out"],["放学","fàngxué","school is over"],
["非","fēi","not"],["非常","fēicháng","extremely"],["分","fēn","minute"],["粉","fěn","pink"],["粉色","fěnsè","pink"],
["服","fú","clothes"],["高","gāo","tall"],["哥哥","gē(ge)","older brother"],["歌","gē","song"],["个","gè","a measure word (for a noun with no particular measure word)"],
["个子","gèzi","height; stature"],["跟","gēn","with"],["工","gōng","work"],["工作","gōngzuò","work"],["公","gōng","public"],
["公共","gōnggòng","public"],["公共汽车","gōnggòng qìchē","public bus"],["共","gòng","common"],["狗","gǒu","dog"],["国","guó","country"],
["果","guǒ","fruit"],["还","hái","also; in addition"],["孩","hái","child"],["行","háng","business firm"],["好","hǎo","good"],
["好","hǎo","used as a polite formula"],["好","hǎo","OK"],["好看","hǎokàn","good-looking; pretty"],["好朋友","hǎo péngyou","good friend"],["好玩儿","hǎowánr","amusing; fun"],
["号","hào","date of a month"],["号","hào","ordinal number"],["号码","hàomǎ","number"],["好","hào","be fond of"],["喝","hē","drink"],
["和","hé","and"],["黑","hēi","black"],["黑色","hēisè","black"],["很","hěn","very"],["很多","hěn duō","a lot of"],
["红","hóng","red"],["红色","hóngsè","red"],["话","huà","word"],["欢","huān","happy"],["黄","huáng","yellow"],
["黄色","huángsè","yellow"],["灰","huī","grey"],["灰色","huīsè","grey"],["会","huì","moment"],["会","huì","can"],
["会儿","huìr","a little while"],["混","hùn","mix"],["混血儿","hùnxuè'ér","person of mixed blood"],["机","jī","machine"],["机器","jīqì","machine"],
["机器人","jīqìrén","robot"],["级","jí","grade"],["几","jǐ","how many"],["家","jiā","family; home"],["家","jiā","expert"],
["见","jiàn","meet with"],["脚","jiǎo","foot"],["叫","jiào","name; call"],["觉","jiào","sleep"],["姐姐","jiě(jie)","older sister"],
["姐妹","jiěmèi","sisters"],["今","jīn","current; present"],["今年","jīnnián","this year"],["今天","jīntiān","today"],["进","jìn","come in"],
["经","jīng","manage"],["经理","jīnglǐ","manager"],["睛","jīng","eyeball"],["九","jiǔ","nine"],["开","kāi","drive"],
["开车","kāichē","drive"],["看","kàn","look; see"],["看","kàn","read"],["看见","kànjiàn","see"],["看书","kàn shū","read a book"],
["可","kě","be worth (doing)"],["可爱","kě'ài","cute; lovely"],["刻","kè","a quarter (of an hour)"],["课","kè","lesson; class"],["口","kǒu","a measure word (for family members)"],
["裤","kù","trousers"],["裤子","kùzi","trousers"],["快","kuài","happy"],["快乐","kuàilè","happy"],["来","lái","come"],
["蓝","lán","blue"],["蓝色","lánsè","blue"],["篮","lán","basket"],["篮球","lánqiú","basketball"],["老","lǎo","(a prefix)"],
["老师","lǎoshī","teacher"],["乐","lè","happy"],["了","le","(a particle)"],["理","lǐ","manage"],["脸","liǎn","face"],
["两","liǎng","two"],["〇","líng","zero"],["零","líng","zero"],["六","liù","six"],["路","lù","road; street"],
["律","lǜ","law"],["律师","lǜshī","lawyer"],["绿","lǜ","green"],["绿色","lǜsè","green"],["妈妈","mā(ma)","mum; mother"],
["马","Mǎ","a surname"],["码","mǎ","number"],["吗","ma","(a particle)"],["忙","máng","busy"],["猫","māo","cat"],
["毛","máo","wool"],["毛","máo","hair; feather"],["毛衣","máoyī","sweater"],["没","méi","not have"],["没有","méiyǒu","not have"],
["每","měi","every"],["每天","měi tiān","every day"],["美国","Měiguó","America"],["美国人","Měiguórén","American (people)"],["妹妹","mèi(mei)","younger sister"],
["们","men","a suffix for plurals"],["秘","mì","secret"],["秘书","mìshū","secretary"],["名","míng","name"],["名字","míngzi","name"],
["明","míng","immediately following in time"],["明天","míngtiān","tomorrow"],["哪","nǎ","which; what"],["哪儿","nǎr","where"],["哪些","nǎxiē","which; what"],
["那","nà","that"],["那儿","nàr","there"],["那些","nàxiē","those"],["呢","ne","(a particle)"],["你","nǐ","you"],
["你们","nǐmen","you (plural)"],["年","nián","year"],["年级","niánjí","grade"],["鸟","niǎo","bird"],["您","nín","you (respectful)"],
["牛","niú","cow"],["牛仔","niúzǎi","cowboy"],["牛仔裤","niúzǎikù","jeans"],["女","nǚ","female; daughter"],["女孩儿","nǚhái'r","girl"],
["胖","pàng","fat; plump"],["跑","pǎo","run"],["跑步","pǎobù","run; jog"],["朋","péng","friend"],["朋友","péngyou","friend"],
["皮","pí","leather"],["皮鞋","píxié","leather shoes"],["七","qī","seven"],["期","qī","a period of time"],["骑","qí","ride"],
["起","qǐ","get up"],["起床","qǐchuáng","get up"],["汽","qì","vapour; steam"],["汽车","qìchē","automobile"],["器","qì","instrument; tool"],
["请","qǐng","please"],["球","qiú","ball"],["去","qù","go"],["裙","qún","skirt"],["裙子","qúnzi","skirt"],
["人","rén","person"],["日","rì","day"],["三","sān","three"],["三十一天","sānshíyī tiān","thirty-one days"],["色","sè","colour"],
["衫","shān","top (clothes)"],["商","shāng","business"],["商人","shāngrén","business person"],["上","shàng","previous"],["上","shàng","go"],
["上班","shàngbān","go to work"],["上海","Shànghǎi","Shanghai"],["上课","shàngkè","attend class"],["上午","shàngwǔ","late morning (usually 09:00–12:00)"],["上学","shàngxué","go to school"],
["上","shang","(a suffix)"],["上","shang","used after a noun to indicate the surface of an object"],["少","shǎo","few; little"],["谁","shéi","who"],["身","shēn","body"],
["身上","shēnshang","on one's body"],["身体","shēntǐ","body"],["什么","shénme","what"],["生","shēng","be born"],["生","shēng","student"],
["生","shēng","(a suffix of certain nouns referring to people)"],["生日","shēngrì","birthday"],["师","shī","teacher; someone with a specialized skill"],["十","shí","ten"],["是","shì","be"],
["室","shì","room"],["手","shǒu","hand"],["手机","shǒujī","mobile phone"],["瘦","shòu","thin; slim"],["书","shū","document; book"],
["水","shuǐ","water"],["水果","shuǐguǒ","fruit"],["睡","shuì","sleep"],["睡觉","shuìjiào","sleep"],["四","sì","four"],
["岁","suì","year (of age)"],["他","tā","he; him"],["他们","tāmen","they; them"],["它","tā","it"],["它们","tāmen","they; them (non-human plural)"],
["她","tā","she; her"],["她们","tāmen","they; them (female)"],["套","tào","cover"],["踢","tī","kick"],["踢足球","tī zúqiú","play football"],
["体","tǐ","body"],["天","tiān","day"],["跳","tiào","jump"],["跳舞","tiàowǔ","dance"],["铁","tiě","iron"],
["听","tīng","listen"],["听音乐","tīng yīnyuè","listen to music"],["同","tóng","same"],["同学","tóngxué","schoolmate"],["头","tóu","head"],
["头发","tóufa","hair"],["腿","tuǐ","leg"],["T恤","T xù","T-shirt"],["外","wài","outside"],["外套","wàitào","jacket; coat"],
["玩","wán","play"],["玩儿","wánr","play"],["晚","wǎn","evening"],["晚饭","wǎnfàn","dinner"],["晚上","wǎnshang","evening; night (usually 18:00–24:00)"],
["王","Wáng","a surname"],["尾","wěi","tail"],["尾巴","wěiba","tail"],["我","wǒ","I; me"],["我们","wǒmen","we; us"],
["五","wǔ","five"],["午","wǔ","noon"],["午饭","wǔfàn","lunch"],["舞","wǔ","dance"],["物","wù","creature"],
["喜","xǐ","be fond of"],["喜欢","xǐhuan","like"],["下","xià","latter"],["下午","xiàwǔ","afternoon (usually 13:00–18:00)"],["现","xiàn","present; current"],
["现在","xiànzài","now"],["小","xiǎo","small"],["小学","xiǎoxué","primary school"],["小学生","xiǎoxuéshēng","primary school student"],["小月","xiǎoyuè","a solar month of 30 days"],
["校","xiào","school"],["校车","xiàochē","school bus"],["校服","xiàofú","school uniform"],["些","xiē","some; a few"],["鞋","xié","shoes"],
["谢","xiè","thank"],["谢谢","xièxie","thanks"],["星","xīng","star"],["星期","xīngqī","week"],["星期日","xīngqīrì","Sunday"],
["星期天","xīngqītiān","Sunday"],["星期一","xīngqīyī","Monday"],["行","xíng","go"],["姓","xìng","surname"],["兄","xiōng","older brother"],
["兄弟","xiōngdì","brothers"],["学","xué","school; study"],["学生","xuéshēng","student"],["学校","xuéxiào","school"],["血","xuè","blood"],
["颜","yán","colour"],["颜色","yánsè","colour"],["眼","yǎn","eye"],["眼睛","yǎnjing","eye"],["养","yǎng","raise; keep"],
["样","yàng","appearance"],["也","yě","also"],["一","yī","one"],["一月","yīyuè","January"],["衣","yī","clothes"],
["衣服","yīfu","clothes"],["医","yī","doctor (of medicine)"],["医生","yīshēng","doctor"],["一个星期","yí gè xīngqī","one week"],["一个月","yí gè yuè","one month"],
["一会儿","yíhuìr","a little while"],["姨","yí","aunt"],["一家人","yì jiā rén","one family"],["一年","yì nián","one year"],["一起","yìqǐ","together"],
["音","yīn","sound"],["音乐","yīnyuè","music"],["银","yín","related to money"],["银行","yínháng","bank"],["银行家","yínhángjiā","banker"],
["英国","Yīngguó","Britain"],["英国人","Yīngguórén","British"],["泳","yǒng","swim"],["游","yóu","swim"],["游泳","yóuyǒng","swim"],
["友","yǒu","friend"],["有","yǒu","have"],["圆","yuán","round"],["月","yuè","month"],["乐","yuè","music"],
["运","yùn","move"],["运动","yùndòng","sports"],["仔","zǎi","young man"],["再","zài","again"],["再见","zàijiàn","good-bye; see you again"],
["在","zài","in; on; at"],["早","zǎo","morning"],["早饭","zǎofàn","breakfast"],["早上","zǎoshang","early morning (usually 05:00–09:00)"],["怎么","zěnme","how"],
["长","zhǎng","grow"],["这","zhè","this"],["这儿","zhèr","here"],["这些","zhèxiē","these"],["真","zhēn","really"],
["只","zhī","a measure word (for small animals)"],["中","zhōng","middle"],["中国","Zhōngguó","China"],["中国人","Zhōngguórén","Chinese (people)"],["中午","zhōngwǔ","noon (usually 12:00–13:00)"],
["中学","zhōngxué","secondary school"],["中学生","zhōngxuéshēng","secondary school student"],["自","zì","self; oneself"],["自行车","zìxíngchē","bicycle"],["字","zì","name"],
["子","zi","(a suffix)"],["棕","zōng","brown"],["棕色","zōngsè","brown"],["走","zǒu","walk"],["走路","zǒulù","walk"],
["足","zú","foot"],["足球","zúqiú","football"],["嘴","zuǐ","mouth"],["嘴巴","zuǐba","mouth"],["昨","zuó","yesterday"],
["昨天","zuótiān","yesterday"],["作","zuò","do"],["坐","zuò","sit"],["坐","zuò","travel by"],["坐地铁","zuò dìtiě","take the underground"],
["做","zuò","do"]
];

// HSK 3.0 Level 2 official vocabulary list (204 words)
const FULL_HSK2 = [
["啊","a","ah (particle)"],["爱好","àihào","hobby"],["白色","báisè","white"],["班","bān","class/shift"],["帮","bāng","help"],["帮忙","bāngmáng","help; do a favor"],["包","bāo","bag"],["本子","běnzi","notebook"],["比","bǐ","compare; than"],["笔","bǐ","pen"],["别","bié","don't"],["不错","búcuò","pretty good"],
["不好意思","bù hǎoyìsi","embarrassed; sorry"],["长","cháng","long"],["车站","chēzhàn","station"],["出","chū","go out"],["床","chuáng","bed"],["出国","chūguó","go abroad"],["出来","chūlái","come out"],["出门","chūmén","go out"],["出去","chūqù","go out"],
["词","cí","word"],["次","cì","time (occurrence)"],["从","cóng","from"],["从小","cóngxiǎo","since childhood"],["错","cuò","wrong"],["打","dǎ","hit; play"],["打车","dǎchē","take a taxi"],["打开","dǎkāi","open"],["但","dàn","but"],["但是","dànshì","but"],["得","de","(complement particle)"],["地","de","(adverbial particle)"],["等","děng","wait"],
["点","diǎn","o'clock; order"],["地铁","dìtiě","subway"],["动","dòng","move"],["懂","dǒng","understand"],["多","duō","many; much"],["饭馆","fànguǎn","restaurant"],["飞","fēi","fly"],["高","gāo","tall"],["告诉","gàosu","tell"],["高中","gāozhōng","high school"],["给","gěi","give"],["跟","gēn","with; follow"],
["个子","gèzi","height; stature"],["公交车","gōngjiāochē","bus"],["过","guò","pass; cross"],["过","guo","(past experience particle)"],["过来","guòlái","come over"],["过年","guònián","celebrate new year"],["过去","guòqù","past; go over"],["还是","háishi","or; still"],["好","hǎo","good"],["黑色","hēisè","black"],
["红茶","hóngchá","black tea"],["红色","hóngsè","red"],["后面","hòumiàn","behind"],["画","huà","draw; painting"],["花","huā","flower"],["花","huā","spend (money/time)"],["坏","huài","bad; broken"],["回来","huílái","come back"],["回去","huíqù","go back"],["间","jiān","room; measure word"],["教","jiāo","teach"],
["教室","jiàoshì","classroom"],["机场","jīchǎng","airport"],["记得","jìde","remember"],["介绍","jièshào","introduce"],["近","jìn","near"],["进","jìn","enter"],["经常","jīngcháng","often"],["进来","jìnlái","come in"],["进去","jìnqù","go in"],
["机票","jīpiào","plane ticket"],["就","jiù","just; then"],["酒店","jiǔdiàn","hotel"],["咖啡","kāfēi","coffee"],["开始","kāishǐ","start"],["开学","kāixué","start school"],["考","kǎo","test (verb)"],["考试","kǎoshì","exam"],["可能","kěnéng","maybe; possible"],["快","kuài","fast"],
["快乐","kuàilè","happy"],["快要","kuàiyào","about to"],["裤子","kùzi","pants"],["篮球","lánqiú","basketball"],["累","lèi","tired"],["离","lí","from; away from"],["里面","lǐmiàn","inside"],["楼","lóu","building; floor"],["路","lù","road"],["绿茶","lǜchá","green tea"],["绿色","lǜsè","green"],
["路上","lùshang","on the way"],["旅游","lǚyóu","travel"],["慢","màn","slow"],["每","měi","every"],["没意思","méi yìsi","boring"],["门","mén","door"],["门口","ménkǒu","doorway"],["门票","ménpiào","entrance ticket"],["面","miàn","side; surface"],["名","míng","name"],["拿","ná","take; hold"],
["那","nà","that"],["奶茶","nǎichá","milk tea"],["奶奶","nǎinai","grandmother (paternal)"],["那么","nàme","so; like that"],["男孩儿","nánháir","boy"],["那样","nàyàng","like that"],["鸟","niǎo","bird"],["女孩儿","nǚháir","girl"],["旁边","pángbiān","beside"],["跑","pǎo","run"],
["跑步","pǎobù","jog"],["票","piào","ticket"],["前面","qiánmiàn","in front"],["起来","qǐlái","get up; stand up"],["晴","qíng","sunny; clear"],["球","qiú","ball"],["妻子","qīzi","wife"],["让","ràng","let; allow"],["肉","ròu","meat"],["商场","shāngchǎng","shopping mall"],
["上来","shànglái","come up"],["上面","shàngmiàn","above; on top"],["上去","shàngqù","go up"],["上网","shàngwǎng","go online"],["生日","shēngrì","birthday"],["身体","shēntǐ","body; health"],["时","shí","time"],
["事情","shìqing","matter; thing"],["手","shǒu","hand"],["手表","shǒubiǎo","watch (wrist)"],["书包","shūbāo","schoolbag"],["舒服","shūfu","comfortable"],["送","sòng","give; send; deliver"],["虽然","suīrán","although"],["所以","suǒyǐ","so; therefore"],["疼","téng","hurt; painful"],["题","tí","question; problem"],
["踢","tī","kick"],["条","tiáo","(measure word, long thin things)"],["跳舞","tiàowǔ","dance"],["头","tóu","head"],["外国","wàiguó","foreign country"],["外面","wàimiàn","outside"],["完","wán","finish"],["万","wàn","ten thousand"],["忘","wàng","forget"],["往","wǎng","toward"],["网上","wǎngshàng","online"],
["位","wèi","(polite measure word for people)"],["为什么","wèishénme","why"],["洗","xǐ","wash"],["下来","xiàlái","come down"],["下面","xiàmiàn","below; next"],["笑","xiào","laugh; smile"],["小孩儿","xiǎoháir","child"],["小时候","xiǎoshíhou","childhood"],
["下去","xiàqù","go down"],["姓","xìng","surname"],["姓名","xìngmíng","full name"],["洗手间","xǐshǒujiān","restroom"],["希望","xīwàng","hope"],["眼睛","yǎnjing","eyes"],["颜色","yánsè","color"],["药","yào","medicine"],
["药店","yàodiàn","pharmacy"],["爷爷","yéye","grandfather (paternal)"],["一会儿","yíhuìr","a moment; a while"],["已经","yǐjīng","already"],["阴","yīn","overcast; cloudy"],["因为","yīnwèi","because"],["一起","yìqǐ","together"],["意思","yìsi","meaning"],["游","yóu","swim"],["右","yòu","right (direction)"],
["右边","yòubian","right side"],["有时","yǒushí","sometimes"],["有意思","yǒu yìsi","interesting"],["游泳","yóuyǒng","swim"],["鱼","yú","fish"],["远","yuǎn","far"],["运动","yùndòng","sports; exercise"],["站","zhàn","stand; station"],
["丈夫","zhàngfu","husband"],["着","zhe","(continuous action particle)"],["这么","zhème","so; like this"],["正","zhèng","exactly; just"],["这样","zhèyàng","like this"],["周","zhōu","week"],["准备","zhǔnbèi","prepare"],["自己","zìjǐ","oneself"],["走","zǒu","walk"],["走路","zǒulù","walk"],["最","zuì","most"],
["左","zuǒ","left"],["左边","zuǒbian","left side"],["足球","zúqiú","football; soccer"],
["北京烤鸭","Běijīng Kǎoyā","Beijing roast duck"],["北京大学","Běijīng Dàxué","Peking University"],["颐和园","Yíhé Yuán","Summer Palace"]
];

// HSK 3.0 Level 3 official vocabulary list (500 new words; source: mandarinbean.com)
const FULL_HSK3 = [
["阿姨","āyí","aunt"],["矮","ǎi","short"],["爱人","àiren","spouse"],["安静","ānjìng","quiet"],["安全","ānquán","safe"],
["把","bǎ","measure word for objects with handles; particle for object-fronting"],["搬","bān","to move, to carry"],["班级","bānjí","class, grade"],["搬家","bānjiā","to move house"],["办","bàn","to do, to handle"],
["办法","bànfǎ","way, solution"],["办公室","bàngōngshì","office"],["半天","bàntiān","half a day, a long time"],["帮助","bāngzhù","help"],["饱","bǎo","full"],
["报纸","bàozhǐ","newspaper"],["北","běi","north"],["北方","běifāng","north"],["被","bèi","by"],["笔记","bǐjì","notes"],
["比较","bǐjiào","to compare; quite, relatively; than"],["笔记本","bǐjìběn","notebook"],["比如","bǐrú","for example"],["比赛","bǐsài","to compete; game, match"],["必须","bìxū","must"],
["变","biàn","to change, to become"],["遍","biàn","measure word for actions"],["变成","biànchéng","to become, to turn into"],["变化","biànhuà","to change; change"],["表演","biǎoyǎn","to perform, to act"],
["别的","biéde","other"],["别人","biérén","other people"],["宾馆","bīnguǎn","hotel"],["冰","bīng","ice; (to freeze)"],["冰激凌","bīngjīlíng","ice cream"],
["冰箱","bīngxiāng","refrigerator"],["病人","bìngrén","patient"],["不但","búdàn","not only"],["不见","bújiàn","to disappear, to not see"],["不用","búyòng","need not"],
["不同","bù tóng","different"],["不久","bùjiǔ","soon, not long after"],["不行","bùxíng","not allowed, won't do; not good"],["才","cái","just, only"],["菜单","càidān","menu"],
["参加","cānjiā","to join, to attend"],["草","cǎo","grass"],["草地","cǎodì","grassland"],["层","céng","measure word for layer, floor"],["查","chá","to check"],
["差","chà","bad, poor; to lack"],["差不多","chàbuduō","almost, similar; nearly"],["尝","cháng","to taste"],["常","cháng","often, frequent"],["常见","cháng jiàn","common"],
["常用","cháng yòng","commonly used"],["常常","chángcháng","often"],["衬衫","chènshān","shirt"],["成绩","chéngjì","score, grade, achievement"],["城市","chéngshì","city"],
["迟到","chídào","to be late"],["出发","chūfā","to set out, to leave"],["出生","chūshēng","to be born"],["出院","chūyuàn","to be discharged from hospital"],["初中","chūzhōng","junior high school"],
["除了","chúle","except, besides"],["船","chuán","boat"],["春天","chūntiān","spring"],["词典","cídiǎn","dictionary"],["聪明","cōngmíng","smart, clever"],
["打扫","dǎsǎo","to clean"],["打算","dǎsuàn","to plan, intend; plan"],["大概","dàgài","general, rough; probably, approximately; (general idea)"],["大人","dàren","adult"],["大小","dàxiǎo","size"],
["大熊猫","dàxióngmāo","giant panda"],["大衣","dàyī","coat"],["带","dài","to bring, to take; (belt)"],["担心","dānxīn","to worry"],["蛋糕","dàngāo","cake"],
["当然","dāngrán","of course"],["到处","dàochù","everywhere"],["得","dé","to get, to obtain"],["得到","dédào","to get, to obtain"],["得分","défēn","to score; score"],
["的话","dehuà","particle used after a condition clause, if…"],["得","děi","must, need"],["灯","dēng","lamp, light"],["地","dì","ground, earth, land"],["地点","dìdiǎn","place, location"],
["地方","dìfang","place"],["地图","dìtú","map"],["电","diàn","electricity; (to give an electric shock)"],["电梯","diàntī","elevator"],["电子书","diànzǐshū","e-book"],
["丢","diū","to lose, to throw away"],["东","dōng","east"],["东北","dōngběi","northeast"],["东方","dōngfāng","east"],["东南","dōngnán","southeast"],
["冬天","dōngtiān","winter"],["懂得","dǒngde","to understand"],["动物","dòngwù","animal"],["动物园","dòngwùyuán","zoo"],["短","duǎn","short"],
["短裤","duǎnkù","shorts"],["段","duàn","measure word of segment, paragraph"],["锻炼","duànliàn","to exercise"],["对话","duìhuà","dialogue, conversation"],["饿","è","hungry"],
["而且","érqiě","and, moreover"],["耳朵","ěrduo","ear"],["耳机","ěrjī","earphone"],["发","fā","to send, to issue"],["发烧","fāshāo","to have a fever"],
["发生","fāshēng","to happen"],["发现","fāxiàn","to find, to discover"],["发展","fāzhǎn","to develop"],["方便","fāngbiàn","convenient"],["方便面","fāngbiànmiàn","instant noodles"],
["方法","fāngfǎ","method"],["方向","fāngxiàng","direction"],["房子","fángzi","house"],["放","fàng","to put, to place"],["放假","fàngjià","to have a holiday"],
["放心","fàngxīn","to relax, to feel at ease"],["放学","fàngxué","school is over"],["分开","fēnkāi","to separate"],["风","fēng","wind"],["封","fēng","measure word for letters; (to seal)"],
["夫妻","fūqī","husband and wife"],["服务","fúwù","to serve"],["附近","fùjìn","nearby"],["复习","fùxí","to review"],["该","gāi","should"],
["干净","gānjìng","clean"],["感兴趣","gǎn xìngqù","to be interested in"],["感到","gǎndào","to feel"],["感冒","gǎnmào","cold; to catch a cold"],["干","gàn","to do, to work"],
["刚","gāng","just, just now"],["刚才","gāngcái","just now"],["刚刚","gānggāng","just now, a moment ago"],["高铁","gāotiě","high-speed rail"],["根据","gēnjù","to base on; according to; (basis)"],
["更","gèng","more"],["公斤","gōngjīn","kilogram"],["公园","gōngyuán","park"],["工作日","gōngzuòrì","workday"],["故事","gùshi","story"],
["刮","guā","to scrape, to blow"],["关","guān","to close, to turn off; pass"],["关机","guānjī","to turn off device"],["关系","guānxì","relationship; (to relate)"],["关心","guānxīn","to care about, to be concerned"],
["关于","guānyú","about, regarding"],["关注","guānzhù","to pay attention to, to follow"],["国家","guójiā","country"],["过节","guòjié","to celebrate a festival"],["过去","guòqù","past"],
["海","hǎi","sea"],["害怕","hàipà","to be afraid"],["好多","hǎoduō","many, a lot"],["好久","hǎojiǔ","a long time"],["好像","hǎoxiàng","to seem, as if; perhaps"],
["号码","hàomǎ","number, code"],["河","hé","river"],["合适","héshì","suitable"],["黑板","hēibǎn","blackboard"],["红绿灯","hóng-lǜdēng","traffic light"],
["后来","hòulái","later, afterwards"],["后年","hòunián","the year after next"],["后天","hòutiān","the day after tomorrow"],["护照","hùzhào","passport"],["花园","huāyuán","garden"],
["画家","huàjiā","painter, artist"],["欢迎","huānyíng","to welcome"],["还","huán","to return, to give back"],["环境","huánjìng","environment"],["换","huàn","to exchange, to change"],
["黄色","huángsè","yellow"],["回答","huídá","to answer"],["会","huì","meeting"],["会议","huìyì","meeting"],["或","huò","or; (perhaps, maybe)"],
["或者","huòzhě","or"],["鸡","jī","chicken"],["几乎","jīhū","almost"],["机会","jīhuì","opportunity"],["极","jí","extremely"],
["急","jí","urgent; (to worry)"],["记","jì","to remember"],["季","jì","season"],["季节","jìjié","season"],["加","jiā","to add"],
["假期","jiàqī","vacation"],["坚持","jiānchí","to persist"],["检查","jiǎnchá","to check, to inspect"],["简单","jiǎndān","simple"],["检票","jiǎnpiào","ticket checking"],
["健康","jiànkāng","healthy"],["见面","jiànmiàn","to meet"],["讲","jiǎng","to speak, to talk"],["角","jiǎo","measure word for fractions, angle, currency"],["脚","jiǎo","foot"],
["接","jiē","to pick up, to receive"],["街","jiē","street"],["节","jié","measure word for segments, sections, lessons; festival, joint; (to save, to control)"],["结婚","jiéhūn","to marry"],["节目","jiémù","program"],
["节日","jiérì","festival"],["结束","jiéshù","to end"],["解决","jiějué","to solve"],["姐妹","jiěmèi","sister"],["借","jiè","to borrow"],
["斤","jīn","catty"],["经过","jīngguò","to pass; process"],["经理","jīnglǐ","manager"],["久","jiǔ","long"],["酒","jiǔ","alcohol"],
["旧","jiù","old"],["句","jù","measure word of sentence"],["句子","jùzi","sentence"],["决定","juédìng","to decide; decision"],["卡","kǎ","card"],
["开花","kāihuā","to bloom"],["开会","kāihuì","to have a meeting"],["开机","kāijī","to turn on device"],["开心","kāixīn","happy"],["看来","kànlái","it seems, it appears"],
["可","kě","but; (yet)"],["渴","kě","thirsty"],["可爱","kě'ài","lovely"],["可是","kěshì","but"],["刻","kè","quarter; to carve"],
["课本","kèběn","textbook"],["客人","kèrén","guest"],["课文","kèwén","text"],["空调","kōngtiáo","air conditioner"],["哭","kū","to cry"],
["筷子","kuàizi","chopsticks"],["矿泉水","kuàngquánshuǐ","mineral water"],["来自","láizì","to come from"],["蓝","lán","blue"],["老","lǎo","old, aged; prefix indicating seniority or endearment; (always, constantly)"],
["老人","lǎorén","elderly person"],["离开","líkāi","to leave"],["礼物","lǐwù","gift"],["历史","lìshǐ","history"],["脸","liǎn","face"],
["练","liàn","to practice"],["练习","liànxí","to practice; exercise"],["凉快","liángkuai","cool"],["辆","liàng","measure word for vehicles"],["聊","liáo","to chat"],
["聊天儿","liáotiānr","to chat"],["了解","liǎojiě","to understand"],["邻居","línjū","neighbor"],["留学","liúxué","to study abroad"],["留学生","liúxuéshēng","overseas student"],
["楼梯","lóutī","stairs"],["路边","lùbiān","roadside"],["路口","lùkǒu","intersection"],["马","mǎ","horse"],["马路","mǎlù","road"],
["马上","mǎshàng","immediately"],["满意","mǎnyì","satisfied"],["毛","máo","measure word for money; (hair)"],["米","mǐ","meter"],["面前","miànqián","in front of"],
["明白","míngbai","to understand; clear"],["名单","míngdān","name list"],["名人","míngrén","famous person"],["南","nán","south"],["难","nán","difficult; (to make difficult)"],
["南方","nánfāng","south"],["难过","nánguò","sad"],["难看","nánkàn","ugly"],["男人","nánrén","man"],["男生","nánshēng","boy student"],
["难题","nántí","difficult problem"],["难听","nántīng","unpleasant to hear"],["年级","niánjí","grade"],["年轻","niánqīng","young"],["牛","niú","cow; (awesome)"],
["努力","nǔlì","to work hard; hardworking"],["女人","nǚrén","woman"],["女生","nǚshēng","girl student"],["爬","pá","to climb"],["怕","pà","to fear; (perhaps)"],
["拍照","pāizhào","to take a photo"],["盘子","pánzi","plate"],["胖","pàng","fat"],["啤酒","píjiǔ","beer"],["平时","píngshí","usually"],
["瓶子","píngzi","bottle"],["骑","qí","to ride"],["奇怪","qíguài","strange"],["其实","qíshí","actually"],["其他","qítā","other"],
["起","qǐ","to rise, to get up; (measure word for events)"],["起飞","qǐfēi","to take off"],["汽车","qìchē","car"],["铅笔","qiānbǐ","pencil"],["前年","qiánnián","the year before last"],
["前天","qiántiān","the day before yesterday"],["清楚","qīngchu","clear, obvious; to understand"],["请假","qǐngjià","to ask for leave"],["请客","qǐngkè","to invite guests, to treat someone"],["秋天","qiūtiān","autumn"],
["球场","qiúchǎng","sports field, court"],["裙子","qúnzi","skirt"],["然后","ránhòu","then, afterwards"],["热情","rèqíng","enthusiastic"],["认得","rènde","to recognize, to know"],
["认为","rènwéi","to think, to consider"],["认真","rènzhēn","serious, earnest"],["容易","róngyì","easy"],["如果","rúguǒ","if"],["伞","sǎn","umbrella"],
["扫","sǎo","to sweep"],["沙发","shāfā","sofa"],["山","shān","mountain"],["上衣","shàngyī","jacket, top garment"],["勺子","sháozi","spoon"],
["身边","shēnbiān","by one's side"],["身高","shēngāo","height"],["声","shēng","sound, voice; measure word for sounds"],["生活","shēnghuó","life; to live"],["生气","shēngqì","to get angry"],
["声音","shēngyīn","sound"],["市","shì","city"],["试","shì","to try"],["室","shì","room"],["世界","shìjiè","world"],
["收","shōu","to receive"],["收到","shōudào","to receive"],["受","shòu","to receive, to be affected"],["瘦","shòu","thin, slim"],["受到","shòudào","to receive, to be subjected to"],
["叔叔","shūshu","uncle"],["树","shù","tree"],["数学","shùxué","mathematics"],["刷","shuā","to brush, to scrub"],["双","shuāng","pair, measure word for pairs"],
["水平","shuǐpíng","level, standard"],["司机","sījī","driver"],["四季","sìjì","four seasons"],["太阳","tàiyáng","sun"],["糖","táng","candy, sugar"],
["特别","tèbié","special; particularly"],["提高","tígāo","to raise, to improve"],["体育","tǐyù","physical education"],["体育馆","tǐyùguǎn","gymnasium"],["甜","tián","sweet"],
["跳","tiào","to jump"],["听说","tīngshuō","to hear said"],["挺","tǐng","quite, rather; (to endure)"],["同事","tóngshì","colleague"],["同意","tóngyì","to agree"],
["头发","tóufa","hair"],["突然","tūrán","sudden"],["图书馆","túshūguǎn","library"],["腿","tuǐ","leg"],["外地","wàidì","other place"],
["外卖","wàimài","takeaway; to order takeout"],["外语","wàiyǔ","foreign language"],["完成","wánchéng","to complete"],["碗","wǎn","bowl"],["晚点","wǎndiǎn","to be late"],
["晚会","wǎnhuì","evening party"],["网球","wǎngqiú","tennis"],["网站","wǎngzhàn","website"],["忘记","wàngjì","to forget"],["为","wèi","for, because of, to"],
["为了","wèile","in order to"],["卫生间","wèishēngjiān","bathroom, restroom"],["文化","wénhuà","culture"],["屋子","wūzi","room, house"],["西","xī","west"],
["西北","xīběi","northwest"],["西方","xīfāng","west"],["西瓜","xīguā","watermelon"],["西南","xīnán","southwest"],["习惯","xíguàn","to be used to; habit"],
["喜爱","xǐ'ài","to like, to love"],["洗衣机","xǐyījī","washing machine"],["洗澡","xǐzǎo","to take a bath"],["夏天","xiàtiān","summer"],["先","xiān","first, before"],
["香蕉","xiāngjiāo","banana"],["相信","xiāngxìn","to believe"],["箱子","xiāngzi","box, case"],["向","xiàng","to face, to turn toward; toward, to"],["像","xiàng","to resemble, to be like; (as if, such as); (image, statue, portrait)"],
["相机","xiàngjī","camera"],["小区","xiǎoqū","residential community"],["小心","xiǎoxīn","to be careful; careful"],["校园","xiàoyuán","campus"],["校长","xiàozhǎng","principal, headmaster"],
["鞋","xié","shoe"],["心里","xīnlǐ","heart, mind"],["新年","xīnnián","New Year"],["新闻","xīnwén","news"],["新鲜","xīnxiān","fresh"],
["信","xìn","to believe; letter"],["信用卡","xìnyòngkǎ","credit card"],["行","xíng","to go; okay, permissible"],["行李","xíngli","luggage"],["兴趣","xìngqù","interest"],
["休假","xiūjià","to take a holiday"],["需要","xūyào","to need; need"],["选","xuǎn","to choose"],["选择","xuǎnzé","to choose"],["学期","xuéqī","semester"],
["牙","yá","tooth"],["牙刷","yáshuā","toothbrush"],["羊","yáng","sheep"],["养","yǎng","to raise, to keep"],["要求","yāoqiú","to demand; requirement"],
["页","yè","measure word for page"],["一定","yídìng","certain; certainly"],["一共","yígòng","altogether, in total"],["一块儿","yíkuàir","the same place; together"],["一样","yíyàng","same"],
["以后","yǐhòu","later, after"],["以前","yǐqián","before"],["以上","yǐshàng","above, more than"],["以外","yǐwài","except, besides"],["以为","yǐwéi","to think, to believe"],
["以下","yǐxià","below, less than"],["一般","yìbān","general, ordinary"],["一边","yìbiān","at the same time"],["一直","yìzhí","always, straight"],["音乐","yīnyuè","music"],
["银行","yínháng","bank"],["银行卡","yínhángkǎ","bank card"],["饮料","yǐnliào","beverage"],["应该","yīnggāi","should, ought to"],["影响","yǐngxiǎng","to affect; influence"],
["用","yòng","to use"],["邮件","yóujiàn","mail"],["游客","yóukè","tourist"],["游戏","yóuxì","game"],["邮箱","yóuxiāng","mailbox"],
["有关","yǒuguān","to have to do with; concerning"],["有名","yǒumíng","famous"],["有用","yǒuyòng","useful"],["又","yòu","again, also"],["羽毛球","yǔmáoqiú","badminton"],
["语言","yǔyán","language"],["雨衣","yǔyī","raincoat"],["遇到","yùdào","to encounter"],["遇见","yùjiàn","to meet"],["园","yuán","garden"],
["员","yuán","suffix for person with a certain job"],["愿意","yuànyì","willing"],["越","yuè","more, increasingly"],["月亮","yuèliang","moon"],["运动会","yùndònghuì","sports meet"],
["运动员","yùndòngyuán","athlete"],["咱们","zánmen","we"],["脏","zāng","dirty"],["怎么办","zěnme bàn","what to do"],["怎样","zěnyàng","how"],
["站","zhàn","to stand; station"],["张","zhāng","to open; measure word for flat objects"],["长","zhǎng","to grow; suffix for head"],["着急","zháojí","anxious"],["照","zhào","to shine, to photograph"],
["照顾","zhàogù","to take care of"],["照片","zhàopiàn","photo"],["照相","zhàoxiàng","to take a picture"],["直到","zhídào","until"],["只","zhǐ","only, merely"],
["纸","zhǐ","paper"],["只能","zhǐ néng","can only"],["只是","zhǐshì","only, merely; but"],["只要","zhǐyào","as long as"],["只有","zhǐyǒu","only if"],
["中","zhōng","middle"],["中间","zhōngjiān","middle, between"],["终于","zhōngyú","finally"],["种","zhǒng","measure word for kinds"],["重要","zhòngyào","important"],
["周末","zhōumò","weekend"],["主要","zhǔyào","main"],["注意","zhùyì","to pay attention to"],["住院","zhùyuàn","to be hospitalized"],["字典","zìdiǎn","dictionary"],
["自行车","zìxíngchē","bicycle"],["子","zi","noun suffix"],["总","zǒng","always, invariably; (to sum up, to assemble; total, overall)"],["总是","zǒngshì","always"],["嘴","zuǐ","mouth"],
["最好","zuìhǎo","best"],["最后","zuìhòu","last, final"],["最近","zuìjìn","recently"],["做客","zuòkè","to be a guest"],["作业","zuòyè","homework"]
];

// HSK 3.0 Level 4 official vocabulary list (1000 new words; source: mandarinbean.com)
const FULL_HSK4 = [
["啊","ā","ah, oh"],["爱情","àiqíng","love"],["爱心","àixīn","compassion, caring"],["安检","ānjiǎn","security check, to conduct security check"],["安排","ānpái","to arrange"],
["按","àn","to press, to push; according to"],["按时","ànshí","on time, on schedule"],["按照","ànzhào","according to, in accordance with"],["白酒","báijiǔ","liquor, spirit"],["办公","bàngōng","to handle official business, to work"],
["办理","bànlǐ","to handle, to process"],["办事","bànshì","to handle matters, to take care of things"],["棒","bàng","great, excellent; (stick, club)"],["保护","bǎohù","to protect"],["保证","bǎozhèng","to guarantee, to ensure; guarantee, assurance"],
["抱","bào","to hold, to embrace, to hug"],["报考","bàokǎo","to apply for an exam, to register for a test"],["报名","bàomíng","to sign up, to register"],["抱歉","bàoqiàn","sorry, apologetic"],["背","bēi","to carry on the back"],
["背包","bēibāo","backpack"],["北部","běibù","northern part, north"],["倍","bèi","measure word meaning times, -fold"],["本科","běnkē","undergraduate program"],["本来","běnlái","original, former; originally, actually"],
["笨","bèn","stupid, foolish"],["鼻子","bízi","nose"],["笔试","bǐshì","written test, to take a written exam"],["毕业","bìyè","to graduate"],["毕业生","bìyèshēng","graduate"],
["便于","biànyú","to be convenient for, to facilitate"],["标准","biāozhǔn","standard; standard, typical"],["表","biǎo","watch, meter, table, form; (to express)"],["表格","biǎogé","form, table"],["表示","biǎoshì","to express, to indicate, to show"],
["表现","biǎoxiàn","to show, to display, to perform"],["表扬","biǎoyáng","to praise, to commend"],["饼干","bǐnggān","biscuit, cracker"],["并","bìng","to combine, to merge; actually, indeed; and, also"],["并且","bìngqiě","and, moreover, furthermore"],
["播放","bōfàng","to broadcast, to play"],["博士","bóshì","doctor"],["不必","búbì","need not, not necessary"],["不便","búbiàn","inconvenient; to be short of money"],["不断","búduàn","continuous, unceasing; continuously, constantly"],
["不够","búgòu","not enough, insufficient; not sufficiently"],["不过","búguò","but, however; (only, merely)"],["不论","búlùn","no matter, regardless"],["步","bù","step, pace"],["部","bù","department, part; measure word for books, machines, etc."],
["不得不","bùdébù","have to, cannot but"],["部分","bùfen","part, portion"],["不管","bùguǎn","no matter, regardless of"],["不光","bùguāng","not only; not only&#8230; (but also)"],["不仅","bùjǐn","not only"],
["不满","bùmǎn","dissatisfied, displeased"],["部门","bùmén","department, unit"],["不如","bùrú","not as good as, inferior to"],["擦","cā","to wipe, to rub"],["猜","cāi","to guess"],
["材料","cáiliào","material, data"],["参观","cānguān","to visit, to tour"],["参赛","cānsài","to enter a competition"],["餐厅","cāntīng","restaurant, dining hall"],["操场","cāochǎng","playground"],
["厕所","cèsuǒ","toilet, restroom"],["查看","chákàn","to check, to view"],["茶叶","cháyè","tea leaf"],["查找","cházhǎo","to search for, to look up"],["差点儿","chàdiǎnr","poor, not good enough; almost, nearly"],
["产生","chǎnshēng","to produce, to generate, to arise"],["厂","chǎng","factory, plant"],["场","chǎng","measure word for events, performances, etc."],["超过","chāoguò","to exceed, to surpass"],["车速","chēsù","vehicle speed"],
["车位","chēwèi","parking space"],["城","chéng","city, town"],["乘","chéng","to ride, to take, to multiply"],["成功","chénggōng","to succeed; successful"],["乘客","chéngkè","passenger"],
["诚实","chéngshí","honest"],["成为","chéngwéi","to become"],["乘坐","chéngzuò","to ride, to take transportation"],["吃惊","chījīng","to be startled, to be shocked"],["迟","chí","late, delayed"],
["重","chóng","again, once more; (to repeat)"],["重新","chóngxīn","again, anew"],["出差","chūchāi","to go on a business trip"],["出口","chūkǒu","exit; (to export)"],["出现","chūxiàn","to appear, to emerge"],
["出行","chūxíng","to travel, to go out"],["出租","chūzū","to rent out"],["厨房","chúfáng","kitchen"],["厨师","chúshī","chef, cook"],["窗","chuāng","window"],
["窗户","chuānghu","window"],["吹","chuī","to blow"],["词语","cíyǔ","word, phrase"],["此","cǐ","this"],["此次","cǐ cì","this time"],
["此外","cǐwài","besides, in addition, moreover"],["从此","cóngcǐ","from then on, since then"],["从来","cónglái","always, at all times"],["从中","cóngzhōng","from among, from it"],["粗","cū","coarse, rough, thick"],
["粗心","cūxīn","careless"],["村","cūn","village"],["存","cún","to store, to keep, to exist"],["错过","cuòguò","to miss, to let slip"],["错误","cuòwù","wrong, mistaken; mistake, error"],
["答应","dāying","to agree, to promise, to reply"],["答","dá","to answer, to reply"],["答案","dá'àn","answer, solution"],["达到","dádào","to reach, to achieve"],["打招呼","dǎ zhāohu","to greet, to say hello"],
["打败","dǎbài","to defeat, to beat"],["打工","dǎgōng","to work a temporary job"],["打扰","dǎrǎo","to disturb, to bother"],["打印","dǎyìn","to print"],["打印机","dǎyìnjī","printer"],
["打折","dǎzhé","to give a discount"],["打针","dǎzhēn","to get an injection, to receive a shot"],["大巴","dàbā","large bus, coach"],["大大","dàdà","greatly, significantly"],["大夫","dàifu","doctor (medical)"],
["大量","dàliàng","large quantity, a large amount"],["大赛","dàsài","major competition, grand contest"],["大厅","dàtīng","hall, lobby"],["大约","dàyuē","approximately, about"],["大自然","dàzìrán","nature, the natural world"],
["待","dāi","to stay"],["戴","dài","to wear, to put on"],["袋子","dàizi","bag, sack"],["单位","dānwèi","unit, department"],["当","dāng","to serve as, to be; at the time of"],
["当时","dāngshí","at that time, then"],["刀","dāo","knife"],["导游","dǎoyóu","tour guide; to guide"],["倒","dào","to fall, to collapse; (however, but)"],["道","dào","path, way, method; measure word for long objects"],
["到底","dàodǐ","finally, after all, to the end"],["到来","dàolái","to arrive"],["道路","dàolù","road, path"],["道歉","dàoqiàn","to apologize"],["得意","déyì","proud, complacent"],
["登机","dēngjī","to board a plane"],["等","děng","and so on, etc.; (class, grade; measure word)"],["等到","děngdào","until, by the time"],["低","dī","low; to lower"],["低价","dījià","low price"],
["低温","dīwēn","low temperature"],["低于","dīyú","to be lower than"],["底","dǐ","bottom, base"],["底下","dǐxia","below, underneath"],["地球","dìqiú","earth"],
["地址","dìzhǐ","address"],["点名","diǎnmíng","to call the roll, to mention by name"],["点头","diǎntóu","to nod"],["电动车","diàndòngchē","electric vehicle, e-bike"],["电视剧","diànshìjù","TV drama"],
["掉","diào","to fall, to drop"],["调查","diàochá","to investigate"],["订","dìng","to order, to book"],["定","dìng","to fix, to set, to determine"],["东部","dōngbù","eastern part"],
["动车","dòngchē","high-speed train"],["动作","dòngzuò","movement, action"],["读者","dúzhě","reader"],["堵车","dǔchē","traffic jam"],["度假","dùjià","to go on vacation"],
["肚子","dùzi","belly, stomach"],["短信","duǎnxìn","text message"],["队","duì","team, squad; (measure word for teams)"],["对方","duìfāng","the other party, counterpart"],["对面","duìmiàn","opposite side"],
["对于","duìyú","regarding, concerning"],["队员","duìyuán","team member"],["队长","duìzhǎng","team leader"],["顿","dùn","measure word for meals, scolding; (to pause)"],["多么","duōme","how, so, what"],
["多数","duōshù","majority"],["多样","duōyàng","diverse, varied"],["而","ér","but, and, yet"],["儿童","értóng","child"],["发出","fāchū","to send out, to issue"],
["发送","fāsòng","to send"],["法","fǎ","law"],["法律","fǎlǜ","law"],["翻译","fānyì","to translate; translation"],["烦","fán","annoyed, vexed; to bother"],
["烦恼","fánnǎo","worried, distressed"],["反对","fǎnduì","to oppose, to be against"],["方面","fāngmiàn","aspect, side"],["方式","fāngshì","way, method"],["房东","fángdōng","landlord"],
["房租","fángzū","rent"],["放弃","fàngqì","to give up"],["放松","fàngsōng","to relax"],["费","fèi","fee, expense; to spend"],["费用","fèiyong","cost, expense"],
["分数","fēnshù","score, grade, fraction"],["分为","fēnwéi","to be divided into"],["份","fèn","measure word for copies, shares"],["丰富","fēngfù","rich, abundant"],["风景","fēngjǐng","scenery, landscape"],
["否则","fǒuzé","otherwise, if not"],["幅","fú","measure word for paintings, photos, etc."],["符合","fúhé","to conform to, to match"],["付","fù","to pay"],["父母","fùmǔ","parents"],
["父女","fùnǚ","father and daughter"],["父亲","fùqīn","father"],["复印","fùyìn","to photocopy, to duplicate"],["复杂","fùzá","complicated, complex"],["负责","fùzé","to be responsible; responsible"],
["负责人","fùzérén","person in charge"],["父子","fùzǐ","father and son"],["改","gǎi","to change, to alter"],["改变","gǎibiàn","to change"],["干","gān","dry; (dried food)"],
["干杯","gānbēi","to toast, cheers"],["赶","gǎn","to hurry, to catch up"],["敢","gǎn","to dare"],["感","gǎn","sense, feeling, as suffix"],["感动","gǎndòng","moved, touched; to move, to touch"],
["赶紧","gǎnjǐn","quickly, promptly"],["感觉","gǎnjué","feeling, sense; to feel"],["赶快","gǎnkuài","quickly, at once"],["感情","gǎnqíng","emotion, feeling"],["感人","gǎnrén","touching, moving"],
["赶上","gǎnshàng","to catch up, to keep up with"],["感受","gǎnshòu","feeling, experience; to feel"],["感谢","gǎnxiè","to thank"],["干活儿","gànhuór","to work"],["钢琴","gāngqín","piano"],
["高价","gāojià","high price"],["高考","gāokǎo","Gaokao, college entrance examination"],["高速","gāosù","high speed"],["高温","gāowēn","high temperature"],["高于","gāoyú","higher than, above"],
["胳膊","gēbo","arm"],["歌声","gēshēng","sound of singing, song"],["歌手","gēshǒu","singer"],["各","gè","each, every; respectively"],["各地","gèdì","various places"],
["各个","gègè","each, every; one by one"],["各位","gèwèi","everyone, all (respectful)"],["各种","gèzhǒng","various kinds, all kinds"],["更加","gèngjiā","more, even more"],["工厂","gōngchǎng","factory"],
["功夫","gōngfu","kung fu, skill, effort"],["公共","gōnggòng","public, common"],["功课","gōngkè","schoolwork, homework"],["公里","gōnglǐ","kilometer"],["公路","gōnglù","highway, road"],
["工人","gōngrén","worker"],["工资","gōngzī","wage, salary"],["共","gòng","together, in total"],["共同","gòngtóng","common, joint"],["够","gòu","enough; sufficiently"],
["购买","gòumǎi","to purchase"],["购物","gòuwù","to shop"],["估计","gūjì","to estimate, to guess"],["姑娘","gūniang","girl"],["鼓励","gǔlì","to encourage"],
["顾客","gùkè","customer"],["故意","gùyì","deliberately, on purpose"],["挂","guà","to hang, to suspend"],["关键","guānjiàn","crux; key, crucial"],["观看","guānkàn","to watch, to view"],
["观众","guānzhòng","audience"],["管","guǎn","control, manage, care about, bother with; (pipe, tube); (measure word for tubular objects)"],["管理","guǎnlǐ","manage"],["光","guāng","light, rayl smooth, shiny, used up; bare, expose; only, merely, solely"],["广播","guǎngbō","broadcast, air; radio broadcast, boradcasting"],
["广告","guǎnggào","advertisement"],["逛","guàng","stroll, roam, browse, shop around"],["规定","guīdìng","stipulate, prescribe, set rules; regulation, rule, stipulation"],["国籍","guójí","nationality"],["国际","guójì","international; world"],
["果汁","guǒzhī","fruit juice"],["过程","guòchéng","process"],["海洋","hǎiyáng","ocean, sea"],["害羞","hàixiū","shy, bshful"],["寒假","hánjià","the winter vacation"],
["寒冷","hánlěng","cold, frigid, chilly"],["喊","hǎn","shout"],["汗","hàn","sweat"],["航班","hángbān","flight"],["好处","hǎochù","benefit"],
["好好","hǎohǎo","good, nice, proper; well, thoroughly, serious, all out"],["好笑","hǎoxiào","funny, ridiculous"],["合格","hégé","qualified"],["盒子","hézi","box"],["红包","hóngbāo","red envelope, red packet"],
["厚","hòu","thick"],["后悔","hòuhuǐ","regret"],["忽然","hūrán","suddenly"],["互联网","hùliánwǎng","Internet"],["护士","hùshi","nurse"],
["互相","hùxiāng","each other"],["话剧","huàjù","drama"],["怀疑","huáiyí","doubt"],["坏处","huàichù","disadvantage, harm"],["环保","huánbǎo","environmental protection; environmentally friendly, green"],
["换乘","huànchéng","transfer, change"],["回复","huífù","reply"],["回信","huíxìn","reply to a letter, write backl; reply letter, response"],["回忆","huíyì","memory"],["会员","huìyuán","membership"],
["活","huó","live; alive, living, flexible; work, job, livelihood"],["活动","huódòng","move, exercise, beactive; activity, event, exercise"],["活泼","huópō","lively"],["火","huǒ","fire; urgent, popular, hot"],["货","huò","goods, commodity, money"],
["获得","huòdé","get"],["获奖","huòjiǎng","win a prize, receive an award"],["获取","huòqǔ","gain, obtain"],["基本","jīběn","basic, fundamental, essential; basically, essentially, on the whole"],["基本上","jīběnshàng","basically"],
["基础","jīchǔ","Basics"],["激动","jīdòng","excited, agitated, emotionally moved; to excite, to agitate, to move (emotionally)"],["积极","jījí","positive"],["积累","jīlěi","to accumulate, to build up, to amass"],["及时","jíshí","timely, prompt, in time; without delay, promptly, in a timely manner"],
["即使","jíshǐ","even if"],["既","jì","already, since; both &#8230; and &#8230;, as well as (used in the pattern 既&#8230;又/也&#8230;)"],["寄","jì","send"],["计划","jìhuà","plan, project, program, scheme; to plan, to map out, to intend"],["既然","jìrán","since"],
["技术","jìshù","technology"],["继续","jìxù","continue"],["记者","jìzhě","reporter"],["加班","jiābān","work overtime"],["家具","jiājù","furniture"],
["加快","jiākuài","speed up, accelerate"],["加强","jiāqiáng","strengthen, reinforce"],["加入","jiārù","add, mix, join, become a member"],["加上","jiāshàng","plus, add,  with the addition of"],["家庭","jiātíng","family"],
["家乡","jiāxiāng","hometown"],["加油","jiāyóu","oil, refuel,  make an all-out effort"],["加油站","jiāyóuzhàn","gas station"],["家长","jiāzhǎng","parent, the head of the family"],["假","jiǎ","false, fake"],
["价格","jiàgé","price"],["价钱","jiàqián","price"],["假日","jiàrì","holiday, day off, vacation"],["减","jiǎn","to reduce, to decrease, to subtract, to lessen"],["减轻","jiǎnqīng","to lighten, to ease, to alleviate, to reduce (burden, weight, pressure)"],
["减少","jiǎnshǎo","to reduce, to decrease, to cut down, to diminish"],["健身","jiànshēn","to exercise, to work out, to keep fit, to engage in fitness activities"],["健身房","jiànshēnfáng","gym"],["建议","jiànyì","to suggest, to propose, to recommend; suggestion, proposal, recommendation"],["江","jiāng","river"],
["将","jiāng","with, by (used to introduce the object of a verb, similar to 把); will, shall, be about to"],["将来","jiānglái","future"],["将要","jiāngyào","will, be going to, be about to"],["奖","jiǎng","prize, award, reward; to award, to reward, to praise"],["奖金","jiǎngjīn","bonus, prize money, cash award"],
["奖学金","jiǎngxuéjīn","scholarship, fellowship"],["降","jiàng","to fall, to drop, to descend, to lower"],["降低","jiàngdī","to reduce, to lower, to bring down"],["降价","jiàngjià","to descend, to land, to touch down"],["降落","jiàngluò","to descend, to land, to touch down"],
["降温","jiàngwēn","to cool down, to lower the temperature"],["交","jiāo","to hand in, to submit; to meet, to cross; to make friends with; friend, acquaintance, relationship"],["骄傲","jiāo'ào","proud, arrogant, conceited; pride, arrogance"],["交警","jiāojǐng","traffic police"],["交流","jiāoliú","communicate"],
["郊区","jiāoqū","suburb"],["交通","jiāotōng","traffic"],["教练","jiàoliàn","coach"],["教师","jiàoshī","teacher"],["教授","jiàoshòu","professor"],
["教学","jiàoxué","teach"],["教育","jiàoyù","education; to educate"],["叫作","jiàozuò","be called, be known as"],["街道","jiēdào","street"],["接受","jiēshòu","accept"],
["接着","jiēzhe","to continue, to follow, to catch; then, next, subsequently"],["结果","jiéguǒ","result, outcome, consequence; as a result, consequently, in the end"],["节假日","jiéjiàrì","festivals and holidays, holiday season"],["节约","jiéyuē","to save, to economize, to conserve"],["结账","jiézhàng","to pay the bill, to settle an account, to check out"],
["解释","jiěshì","to explain, to interpret, to account for"],["今后","jīnhòu","from now on, in the future, henceforth"],["仅","jǐn","only, merely, solely"],["尽管","jǐnguǎn","feel free to, not hesitate to (often in the pattern 尽管 + verb); although, even though, despite"],["仅仅","jǐnjǐn","only, merely, barely, simply"],
["紧张","jǐnzhāng","nervous, tense, strained, in short supply"],["进入","jìnrù","to enter, to access, to be admitted to"],["进行","jìnxíng","to carry out, to conduct, to proceed with, to undertake"],["禁止","jìnzhǐ","to prohibit, to forbid, to ban"],["精彩","jīngcǎi","brilliant, splendid, wonderful, exciting"],
["经济","jīngjì","economy, economics; economical, affordable"],["京剧","jīngjù","Beijing opera"],["经历","jīnglì","to experience, to go through; experience, past, history"],["经验","jīngyàn","experience"],["警察","jǐngchá","police"],
["景点","jǐngdiǎn","scenic spot, tourist attraction, point of interest"],["景区","jǐngqū","scenic area, tourist attraction zone"],["景色","jǐngsè","scenery"],["竟然","jìngrán","unexpectedly"],["竞争","jìngzhēng","compete"],
["镜子","jìngzi","mirror"],["究竟","jiūjìng","actually, exactly, after all (used for emphasis in questions); the outcome, the details of a situation"],["就是","jiùshì","precisely, exactly (used for emphasis); only, merely, simply; even if, even (as in 就是&#8230;也&#8230;)"],["举","jǔ","to raise, to lift; to hold (an event); to give (an example); to recommend"],["举办","jǔbàn","to hold, to host, to organize (an event, activity)"],
["举例","jǔlì","to give an example, to illustrate with an example"],["举行","jǔxíng","to hold, to convene, to conduct (a ceremony, meeting, event)"],["聚","jù","to gather, to assemble, to get together"],["聚餐","jùcān","to have a dinner together, to dine together"],["聚会","jùhuì","to get together, to meet, to gather; party, gathering, meeting"],
["拒绝","jùjué","to refuse, to reject, to decline"],["距离","jùlí","to be away from, to be at a distance from; distance, gap"],["剧院","jùyuàn","theater, opera house, playhouse"],["开玩笑","kāi wánxiào","make fun of"],["看法","kànfǎ","view"],
["烤","kǎo","to bake, to roast, to grill, to toast"],["考虑","kǎolǜ","to consider, to think over, to contemplate"],["考生","kǎoshēng","examinee"],["棵","kē","measure word for trees, plants, and other similar objects"],["科技","kējì","science and technology"],
["科学","kēxué","science; scientific"],["咳","ké","to cough"],["咳嗽","késou","to cough"],["可惜","kěxī","regrettable, unfortunate, a pity"],["克","kè","gram"],
["课程","kèchéng","curriculum"],["客气","kèqi","polite, courteous; to be polite, to say polite remarks"],["课堂","kètáng","classroom"],["客厅","kètīng","living room, parlor"],["肯定","kěndìng","to be certain, to be sure, to affirm; positive, affirmative, definite; surely, certainly, definitely"],
["空","kōng","empty, vacant, hollow; （in vain, for nothing）"],["空气","kōngqì","atmosphere, air"],["恐怕","kǒngpà","to fear, to be afraid; I'm afraid, perhaps, maybe"],["空","kòng","to leave empty, to make time, to free up; empty, free, unoccupied; free time, empty space"],["口语","kǒuyǔ","spoken language"],
["苦","kǔ","bitter"],["快餐","kuàicān","fast food"],["快递","kuàidì","express delivery"],["快速","kuàisù","fast, high-speed"],["困","kùn","sleepy, tired; （to trap, to confine）"],
["困难","kùnnan","difficult, hard; difficulty, trouble"],["拉","lā","to pull, to drag, to draw"],["垃圾","lājī","garbage, trash, rubbish"],["辣","là","hot, spicy"],["来不及","láibují","there's not enough time, it's too late"],
["来得及","láidejí","there's still time, can make it in time"],["懒","lǎn","lazy, idle"],["浪费","làngfèi","to waste, to squander"],["浪漫","làngmàn","romantic"],["老虎","lǎohǔ","tiger"],
["老家","lǎojiā","hometown, home state"],["老年","lǎonián","elderly"],["老是","lǎoshì","always, constantly"],["冷静","lěngjìng","calm, cool-headed"],["理发","lǐfà","to have a haircut, to cut hair"],
["理解","lǐjiě","to understand, to comprehend"],["礼貌","lǐmào","courtesy, politeness; polite"],["理想","lǐxiǎng","ideal, dream; ideal"],["厉害","lìhai","severe, fierce, impressive, excellent"],["力气","lìqi","strength, physical power"],
["例如","lìrú","for example, such as"],["例子","lìzi","example, instance"],["俩","liǎ","two, both"],["连","lián","used to introduce the object of a verb, linking; (even, including); (to connect, to link)"],["联系","liánxì","to contact, to connect"],
["凉","liáng","cool, cold"],["量","liáng","to measure, to weigh"],["两","liǎng","measure word for vehicles, animals, etc."],["亮","liàng","bright, light; to shine, to show"],["列","liè","to arrange in a row, to list; measure word for rows or lines"],
["零下","líng xià","below zero"],["零花钱","línghuāqián","pocket money, spending money"],["零钱","língqián","change, small denominations of money"],["零食","língshí","snacks, between-meal nibbles"],["另","lìng","other, another; (separately, otherwise)"],
["另外","lìngwài","other, else; in addition, moreover; besides, furthermore"],["留","liú","to stay, to remain, to keep"],["流","liú","to flow, to circulate"],["流利","liúlì","fluent, smooth"],["留下","liúxia","to leave behind, to remain"],
["流行","liúxíng","to be popular, to be in fashion, to spread"],["路过","lùguò","to pass by, to go by"],["旅馆","lǚguǎn","hotel, inn"],["旅客","lǚkè","traveler, passenger"],["旅行","lǚxíng","to travel"],
["律师","lǜshī","lawyer, attorney"],["乱","luàn","messy, disorderly; arbitrarily, recklessly"],["落","luò","to fall, to drop, to land"],["麻烦","máfan","troublesome, annoying; to trouble, to bother; trouble, inconvenience"],["馒头","mántou","steamed bun, mantou"],
["满","mǎn","full, filled; to fill"],["毛巾","máojīn","towel"],["毛衣","máoyī","sweater, woolen garment"],["帽子","màozi","hat, cap"],["美","měi","beautiful, pretty"],
["美好","měihǎo","beautiful, splendid"],["美景","měijǐng","beautiful scenery"],["美丽","měilì","beautiful, lovely"],["美食","měishí","delicious food, cuisine"],["梦","mèng","dream; to dream"],
["梦想","mèngxiǎng","to dream; dream"],["密码","mìmǎ","password, PIN code"],["免费","miǎnfèi","free of charge, to be free"],["面对","miànduì","to face, to confront"],["面试","miànshì","interview, audition; to interview"],
["秒","miǎo","second, unit of time"],["民族","mínzú","ethnic group, nationality"],["末","mò","end, last"],["母女","mǔnǚ","mother and daughter"],["母亲","mǔqīn","mother"],
["母子","mǔzǐ","mother and son"],["目标","mùbiāo","goal, target, objective"],["目的","mùdì","purpose, aim, goal"],["目的地","mùdìdì","destination"],["目前","mùqián","currently, at present"],
["耐心","nàixīn","patient; patience"],["南部","nánbù","southern part, south"],["难道","nándào","could it be that&#8230;?"],["男士","nánshì","man, gentleman"],["难受","nánshòu","uncomfortable, painful, hard to bear"],
["难忘","nánwàng","unforgettable, to be hard to forget"],["男性","nánxìng","male, masculine"],["内","nèi","inside, within"],["内容","nèiróng","content, substance"],["内心","nèixīn","heart, inner self"],
["能否","néng fǒu","whether or not, can or cannot"],["能够","nénggòu","can, be able to, be capable of"],["能力","nénglì","ability, capability, capacity"],["嗯","ǹg","uh-huh, hmm"],["年底","niándǐ","end of the year"],
["年龄","niánlíng","age"],["农村","nóngcūn","rural area, countryside"],["弄","nòng","to do, to handle, to mess with"],["女性","nǚxìng","female, feminine"],["暖和","nuǎnhuo","warm; to warm up"],
["偶尔","ǒu'ěr","occasionally, sometimes; occasional"],["拍","pāi","to pat, to clap, to take (a photo); beat, rhythm"],["排","pái","to line up, to arrange; row, line; measure word for rows"],["牌","pái","card, brand, plaque, sign"],["排队","páiduì","to line up, to queue up"],
["排球","páiqiú","volleyball"],["牌子","páizi","brand, sign, label"],["判断","pànduàn","to judge, to determine"],["陪","péi","to accompany, to keep someone company"],["批评","pīpíng","to criticize"],
["皮肤","pífū","skin"],["脾气","píqi","temperament, disposition, temper"],["皮鞋","píxié","leather shoes"],["篇","piān","measure word for essays, articles, papers; piece, sheet"],["片","piàn","piece, slice, area; measure word for flat objects"],
["乒乓球","pīngpāngqiú","table tennis, ping-pong"],["平常","píngcháng","ordinary, usual; usually, ordinarily"],["破","pò","broken, damaged; to break, to ruin"],["葡萄","pútao","grape"],["葡萄酒","pútaojiǔ","wine, grape wine"],
["普遍","pǔbiàn","widespread, universal, common"],["普通","pǔtōng","ordinary, common"],["普通话","pǔtōnghuà","Mandarin Chinese, standard Chinese"],["期","qī","period, phase; measure word for issues, semesters, etc."],["期末","qīmò","end of term, end of semester"],
["期中","qīzhōng","midterm, middle of the term"],["其次","qícì","next, secondly, then"],["其中","qízhōng","among them, inside"],["起到","qǐdào","to play the role of, to function as, to act as"],["气","qì","air, gas, breath; to anger, to make angry"],
["气候","qìhòu","climate"],["汽水","qìshuǐ","soda, soft drink"],["气温","qìwēn","air temperature"],["千克","qiānkè","kilogram"],["千万","qiānwàn","ten million, by all means, absolutely"],
["签证","qiānzhèng","visa; to issue a visa"],["前方","qiánfāng","ahead, front"],["前后","qiánhòu","front and back, around, about"],["强","qiáng","strong, powerful"],["敲","qiāo","to knock, to tap, to strike"],
["桥","qiáo","bridge"],["巧","qiǎo","skillful, clever, opportune"],["巧克力","qiǎokèlì","chocolate"],["亲戚","qīnqi","relative, relative family member"],["琴","qín","musical instrument, piano, etc."],
["轻","qīng","light, not heavy, gentle, easy"],["青年","qīngnián","youth, young people"],["轻松","qīngsōng","relaxed, light, easy"],["情况","qíngkuàng","situation, circumstance"],["庆祝","qìngzhù","to celebrate"],
["球队","qiúduì","sports team, ball team"],["球迷","qiúmí","fan, sports enthusiast"],["区","qū","district, area, region"],["区别","qūbié","difference; to distinguish, to differ"],["取","qǔ","to take, to get, to obtain"],
["取得","qǔdé","to obtain, to gain"],["取消","qǔxiāo","to cancel, to call off"],["全","quán","whole, entire; completely, entirely"],["全部","quánbù","all, the whole thing"],["全都","quándōu","all, entirely"],
["全球","quánqiú","the whole world, global"],["全身","quánshēn","whole body"],["缺","quē","to lack, to be short of"],["缺点","quēdiǎn","shortcoming, defect"],["缺少","quēshǎo","to lack, to be short of"],
["却","què","but, yet, however"],["确实","quèshí","indeed, really"],["然而","rán'ér","however, but"],["热闹","rènao","lively, bustling; to liven up; lively atmosphere"],["人生","rénshēng","life"],
["人数","rénshù","number of people"],["人员","rényuán","personnel, staff"],["任何","rènhé","any, whatever"],["任务","rènwu","task, assignment, mission"],["扔","rēng","to throw, to toss"],
["仍","réng","still, yet"],["仍然","réngrán","still, yet"],["日常","rìcháng","daily, everyday"],["日记","rìjì","diary"],["日期","rìqī","date"],
["日子","rìzi","day, life, time"],["入","rù","to enter, to go in"],["入口","rùkǒu","entrance"],["入学","rùxué","to enter school, to enroll"],["入住","rùzhù","to check in, to move in"],
["散步","sànbù","to take a walk, to stroll"],["扫码","sǎomǎ","to scan a code"],["森林","sēnlín","forest"],["商量","shāngliang","to discuss, to consult"],["商品","shāngpǐn","product, commodity"],
["伤心","shāngxīn","sad, heartbroken"],["上门","shàngmén","to visit, to go to someone's house"],["稍","shāo","a little, slightly"],["稍微","shāowēi","a little, slightly"],["少见","shǎojiàn","rare, seldom seen"],
["少量","shǎoliàng","small amount, a little"],["少数","shǎoshù","minority, small number"],["少年","shàonián","juvenile, teenager, youth"],["社会","shèhuì","society, community"],["摄氏度","shèshìdù","degrees Celsius"],
["身","shēn","body, oneself; measure word for clothes"],["深","shēn","deep, profound; (deeply, late)"],["身份证","shēnfènzhèng","ID card, identification card"],["申请","shēnqǐng","to apply, to file an application"],["甚至","shènzhì","even, so much as that"],
["生","shēng","to give birth, to produce, to grow"],["生","shēng","raw, uncooked, unripe; （very, extremely, terribly）"],["生命","shēngmìng","life"],["生意","shēngyi","business, trade"],["省","shěng","province"],
["剩","shèng","to be left over, to remain"],["失败","shībài","to fail; failed, unsuccessful"],["师傅","shīfu","master, skilled worker, respectful address for a tradesperson"],["失去","shīqù","to lose, to be lost"],["师生","shīshēng","teacher and student, teachers and students"],
["失望","shīwàng","to be disappointed, to lose hope; disappointed"],["十分","shífēn","very, extremely, fully"],["实际","shíjì","reality, actuality; actual, practical"],["时间表","shíjiānbiǎo","schedule, timetable"],["实际上","shíjìshàng","actually, in fact"],
["食品","shípǐn","food, provisions"],["食堂","shítáng","cafeteria, dining hall"],["食物","shíwù","food"],["实在","shízài","honest, reliable; really, indeed"],["十字路口","shízì lùkǒu","intersection, crossroads"],
["使","shǐ","to make, to cause, to use"],["使馆","shǐguǎn","embassy"],["使用","shǐyòng","to use, to employ"],["市场","shìchǎng","market, marketplace"],["是否","shìfǒu","whether or not, if"],
["适合","shìhé","to suit, to fit, to be suitable"],["世纪","shìjì","century"],["视频","shìpín","video, video clip"],["市区","shìqū","urban area, city center"],["试题","shìtí","test questions, exam paper"],
["适应","shìyìng","to adapt, to fit, to suit"],["收费","shōufèi","to charge a fee, to collect payment"],["收入","shōurù","to receive, to take in; income, revenue"],["收拾","shōushi","to put in order, to tidy up, to pack"],["收听","shōutīng","to listen in, to tune in"],
["首","shǒu","measure word for songs, poems, etc."],["首都","shǒudū","capital"],["首先","shǒuxiān","first, firstly; first of all"],["受不了","shòubuliǎo","to be unable to bear, to be unable to stand"],["售票员","shòupiàoyuán","ticket seller, conductor"],
["受伤","shòushāng","to be injured, to get hurt"],["输","shū","to lose, to be defeated; to transport"],["熟","shú/shóu","ripe, cooked, mature"],["熟悉","shúxi","to be familiar with, to know well"],["暑假","shǔjià","summer vacation"],
["数","shù","number, figure; several, a few"],["数量","shùliàng","quantity, amount"],["树林","shùlín","woods, forest"],["数字","shùzì","digit, figure, number"],["帅","shuài","handsome, good-looking"],
["顺便","shùnbiàn","conveniently, in passing"],["顺利","shùnlì","smooth, successful, going well"],["顺序","shùnxù","order, sequence"],["说法","shuōfǎ","way of saying something, version, statement"],["说明","shuōmíng","to explain, to clarify; explanation, instructions"],
["说明书","shuōmíngshū","instruction manual, user guide, explanatory booklet"],["硕士","shuòshì","master"],["死","sǐ","to die, to be dead; dead, extreme; extremely, to death"],["速度","sùdù","speed"],["塑料","sùliào","plastic"],
["酸","suān","sour, tart"],["酸奶","suānnǎi","yogurt"],["算","suàn","to calculate, to count; considered, at last"],["随便","suíbiàn","to do as one pleases, casual; casual, informal; anyway, whatever"],["随着","suízhe","along with, following"],
["孙女","sūnnǚ","granddaughter"],["孙子","sūnzi","grandson"],["所有","suǒyǒu","all, every; (to possess, to own; possessions, belongings)"],["台","tái","measure word for machines, vehicles, etc.; (platform, stage)"],["抬","tái","to lift, to raise"],
["抬头","táitóu","to raise one's head, to look up"],["态度","tàidù","attitude, manner"],["弹","tán","to play , to spring"],["谈","tán","to talk, to discuss"],["汤","tāng","soup"],
["躺","tǎng","to lie down"],["趟","tàng","measure word for trips, journeys"],["讨论","tǎolùn","to discuss, to talk over"],["讨厌","tǎoyàn","disgusting, annoying; to dislike, to loathe"],["特点","tèdiǎn","characteristic, feature"],
["提","tí","to carry, to lift, to mention, to bring up"],["提出","tíchū","to put forward, to propose, to raise"],["提到","tídào","to mention, to refer to"],["提供","tígōng","to provide, to supply, to offer"],["提前","tíqián","to advance, to move up, to do something ahead of time"],
["提醒","tíxǐng","to remind, to alert"],["体检","tǐjiǎn","to undergo a physical examination, to have a medical checkup"],["体温","tǐwēn","body temperature"],["体重","tǐzhòng","body weight"],["填写","tiánxiě","to fill in, to complete (a form)"],
["条件","tiáojiàn","condition, requirement, terms"],["听力","tīnglì","listening ability, hearing"],["听众","tīngzhòng","audience, listeners"],["停","tíng","to stop, to halt"],["停车","tíngchē","to park, to stop a vehicle"],
["停车场","tíngchēchǎng","parking lot"],["停止","tíngzhǐ","to stop, to cease"],["通","tōng","to go through, to be open; to lead to, to connect; (measure word for whole sets)"],["通过","tōngguò","to pass through, to go through; by means of"],["通知","tōngzhī","to notify, to inform; notice, notification"],
["童年","tóngnián","childhood"],["同时","tóngshí","at the same time; meanwhile, moreover"],["同样","tóngyàng","same, similar"],["桶","tǒng","bucket, barrel"],["痛","tòng","painful, sore; (extremely, bitterly)"],
["头痛","tóutòng","headache"],["图","tú","picture, drawing, diagram; (to plan, to scheme)"],["图片","túpiàn","picture, image, photograph"],["土","tǔ","earth, soil, land; (rustic, unrefined)"],["推","tuī","to push, to shove"],
["推迟","tuīchí","to postpone, to delay"],["推出","tuīchū","to launch, to push out, to introduce"],["脱","tuō","to take off, to shed"],["袜子","wàzi","socks"],["外出","wàichū","to go out, to leave home"],
["外套","wàitào","coat, jacket"],["完全","wánquán","complete, total; completely, absolutely"],["晚安","wǎn'ān","good night"],["晚餐","wǎncān","dinner, supper"],["网购","wǎnggòu","to shop online"],
["往往","wǎngwǎng","often, frequently"],["网页","wǎngyè","webpage"],["网友","wǎngyǒu","netizen, internet user"],["网址","wǎngzhǐ","website URL, web address"],["危险","wēixiǎn","dangerous; danger"],
["为","wéi","to do, to act, to serve as"],["味","wèi","taste, flavor"],["味道","wèidào","taste, flavor"],["卫生","wèishēng","hygiene, sanitation; clean, hygienic"],["温度","wēndù","temperature"],
["闻","wén","to smell, to sniff"],["文件","wénjiàn","document, file"],["文章","wénzhāng","essay, article"],["文字","wénzì","writing, character"],["污染","wūrǎn","contaminated"],
["无","wú","to lack, to not have"],["无法","wúfǎ","unable, incapable"],["无聊","wúliáo","boring, dull"],["无论","wúlùn","no matter what, regardless"],["午餐","wǔcān","lunch"],
["误会","wùhuì","to misunderstand; misunderstanding"],["吸","xī","to suck, to inhale, to absorb"],["西部","xībù","western region, west part"],["西红柿","xīhóngshì","tomato"],["吸引","xīyǐn","to attract"],
["细","xì","thin, fine, detailed"],["细心","xìxīn","careful, attentive"],["下降","xiàjiàng","to decline, to drop, to go down"],["鲜","xiān","fresh"],["鲜花","xiānhuā","fresh flower"],
["咸","xián","salty"],["现金","xiànjīn","cash"],["羡慕","xiànmù","to envy, to admire"],["线上","xiànshàng","online, on the internet"],["线下","xiànxià","offline"],
["现有","xiànyǒu","existing, currently available; to have currently"],["香","xiāng","fragrant"],["相比","xiāngbǐ","to compare with, to contrast"],["相反","xiāngfǎn","opposite, contrary; on the contrary"],["相互","xiānghù","mutual, each other"],
["相同","xiāngtóng","same, identical"],["详细","xiángxì","detailed, thorough"],["响","xiǎng","to make a sound, to ring; loud"],["想法","xiǎngfǎ","thought, idea, opinion"],["项","xiàng","measure word for projects, items"],
["消息","xiāoxi","news, message, information"],["小吃","xiǎochī","snack, light meal"],["小伙子","xiǎohuǒzi","young man, lad"],["小说","xiǎoshuō","novel, fiction"],["小组","xiǎozǔ","small group, team"],
["效果","xiàoguǒ","effect, result"],["笑话","xiàohua","joke, laughter; to joke, to laugh at"],["血","xiě","blood"],["心","xīn","heart"],["辛苦","xīnkǔ","hard, laborious; to work hard, to toil"],
["心情","xīnqíng","mood, feeling"],["信号","xìnhào","signal"],["信息","xìnxī","information, message"],["信心","xìnxīn","confidence, faith"],["兴奋","xīngfèn","excited, thrilled; to excite, to get excited"],
["星星","xīngxing","star"],["醒","xǐng","to wake up, to sober up"],["性","xìng","suffix meaning nature, character, quality"],["性别","xìngbié","gender, sex"],["幸福","xìngfú","happiness; happy, blissful"],
["性格","xìnggé","character"],["兄弟","xiōngdì","brothers"],["熊","xióng","bear"],["修","xiū","to repair, to fix"],["修理","xiūlǐ","to repair, to fix"],
["许多","xǔduō","many, numerous"],["学费","xuéfèi","tuition fee"],["学院","xuéyuàn","college, academy, institute"],["压","yā","to press, to push down, to weigh down"],["压力","yālì","pressure, stress"],
["牙膏","yágāo","toothpaste"],["亚洲","Yàzhōu","Asia"],["烟","yān","cigarette, smoke, mist"],["盐","yán","salt"],["严格","yángé","strict, stringent; to restrict strictly"],
["研究","yánjiū","to research, to study"],["研究生","yánjiūshēng","graduate student, postgraduate"],["严重","yánzhòng","serious, severe, grave"],["演","yǎn","to act, to perform, to play"],["演唱","yǎnchàng","to sing, to perform vocally"],
["演出","yǎnchū","to perform, to put on a show"],["眼镜","yǎnjìng","eyeglasses, glasses"],["眼前","yǎnqián","before one's eyes, at the moment"],["演员","yǎnyuán","actor, performer"],["阳光","yángguāng","sunlight, sunshine"],
["养成","yǎngchéng","to develop, to cultivate, to form"],["样子","yàngzi","appearance, look, manner"],["邀请","yāoqǐng","to invite"],["要是","yàoshi","if, suppose"],["钥匙","yàoshi","key"],
["也许","yěxǔ","maybe, perhaps"],["夜","yè","night; measure word for segments of the night"],["夜晚","yèwǎn","night, evening"],["叶子","yèzi","Leaf"],["一切","yíqiè","everything"],
["已","yǐ","already"],["以内","yǐnèi","within"],["意见","yìjiàn","opinion"],["一生","yìshēng","lifetime, all one's life"],["艺术","yìshù","art"],
["因此","yīncǐ","therefore"],["引起","yǐnqǐ","cause"],["印象","yìnxiàng","impression"],["赢","yíng","win"],["赢得","yíngdé","gain, win"],
["应聘","yìngpìn","to apply for a job, to respond to a job advertisement"],["勇敢","yǒnggǎn","brave, courageous"],["永远","yǒngyuǎn","forever, always; eternity, forever"],["用来","yònglái","to be used for, to serve as"],["用于","yòngyú","to be used for, to be applied to"],
["优点","yōudiǎn","advantage, merit, strong point"],["幽默","yōumò","humorous"],["优秀","yōuxiù","excellent, outstanding"],["由","yóu","by, through, from, because of"],["油","yóu","oil, fat, grease"],
["尤其","yóuqí","especially, particularly"],["游玩","yóuwán","to play, to have fun, to go sightseeing"],["由于","yóuyú","because of, due to; owing to"],["友好","yǒuhǎo","friendly"],["友情","yǒuqíng","friendship"],
["有趣","yǒuqù","interesting, enjoyable, fun"],["有效","yǒuxiào","effective, to be effective"],["友谊","yǒuyì","friendship"],["有着","yǒuzhe","to have, to possess"],["愉快","yúkuài","pleasant, cheerful"],
["于是","yúshì","therefore, hence, so"],["与","yǔ","with, and"],["语法","yǔfǎ","grammar"],["预习","yùxí","to preview, to prepare"],["原来","yuánlái","original, former; originally, actually"],
["原谅","yuánliàng","to forgive, to excuse, to pardon"],["原因","yuányīn","cause, reason"],["远离","yuǎnlí","to stay away from, to keep away from"],["院长","yuànzhǎng","dean, head of a college or institute"],["院子","yuànzi","courtyard, yard"],
["约","yuē","to make an appointment, to arrange; about, approximately"],["约会","yuēhuì","to date, to meet up; date, appointment"],["月饼","yuèbing","mooncake"],["阅读","yuèdú","to read, to read aloud"],["月份","yuèfèn","month"],
["云","yún","cloud"],["允许","yǔnxǔ","to permit, to allow, to give permission"],["杂志","zázhì","magazine"],["再次","zàicì","once again, once more"],["再说","zàishuō","to put off, to postpone; besides, moreover"],
["暂时","zànshí","temporary, for the time being"],["暂停","zàntíng","to suspend, to pause"],["早餐","zǎocān","breakfast"],["早晨","zǎochen","morning"],["责任","zérèn","responsibility, duty"],
["增加","zēngjiā","to increase, to add, to raise"],["增长","zēngzhǎng","to increase, to grow, to rise"],["招聘","zhāopìn","to recruit, to hire"],["着","zháo","to touch, to get to, to catch (fire)"],["着火","zháohuǒ","to catch fire, to ignite"],
["者","zhě","suffix meaning person, one who"],["真正","zhēnzhèng","true, genuine; truly, indeed"],["整","zhěng","whole, complete, entire"],["整个","zhěnggè","whole, entire, all"],["整理","zhěnglǐ","to arrange, to put in order, to tidy up"],
["证","zhèng","certificate, proof, evidence"],["正常","zhèngcháng","normal, regular, proper"],["正好","zhènghǎo","exactly right, just in time; coincidentally"],["证件","zhèngjiàn","ID card, credentials, identification papers"],["证明","zhèngmíng","to prove, to demonstrate; proof, certificate"],
["正确","zhèngquè","correct, right, accurate"],["正式","zhèngshì","formal, official"],["之","zhī","auxiliary word (classical)"],["支持","zhīchí","to support, to back"],["支付","zhīfù","to pay (money)"],
["之后","zhīhòu","after, later, behind"],["之间","zhījiān","between, among"],["之前","zhīqián","before, prior to"],["知识","zhīshi","knowledge"],["之中","zhīzhōng","among, inside"],
["值","zhí","to be worth, to be equal in value; valuable, worthwhile"],["值得","zhídé","to be worth, to deserve"],["直接","zhíjiē","direct, straightforward"],["植物","zhíwù","plant, vegetation"],["职业","zhíyè","occupation, profession"],
["指","zhǐ","to point to, to indicate"],["指出","zhǐchū","to point out, to indicate"],["只好","zhǐhǎo","have to, be forced to"],["纸巾","zhǐjīn","tissue paper, napkin"],["质量","zhìliàng","quality"],
["至少","zhìshǎo","at least"],["中餐","zhōngcān","Chinese food, Chinese meal"],["中年","zhōngnián","middle age"],["种","zhòng","to plant, to grow"],["重","zhòng","weight, importance; heavy, important"],
["重点","zhòngdiǎn","key point, emphasis; mainly, emphatically"],["重视","zhòngshì","to pay attention to, to value"],["周围","zhōuwéi","around, surrounding"],["主意","zhǔyi","idea, thought, plan"],["祝","zhù","to wish, to express good wishes"],
["祝贺","zhùhè","to congratulate, to offer congratulations"],["著名","zhùmíng","famous, well-known"],["专门","zhuānmén","specially, specifically; special"],["专业","zhuānyè","specialty, major; professional, specialized"],["转","zhuǎn","to turn, to shift, to transfer"],
["转发","zhuǎnfā","to forward (a message), to retweet"],["转机","zhuǎnjī","to transfer (flight), to change planes"],["赚","zhuàn","to earn, to make a profit"],["装","zhuāng","to load, to pack, to pretend, to install"],["准","zhǔn","accurate, exact, standard; (definitely, certainly)"],
["准确","zhǔnquè","accurate, precise"],["准时","zhǔnshí","on time, punctual"],["资料","zīliào","materials, data, information"],["仔细","zǐxì","careful, attentive, meticulous"],["自","zì","from, since, oneself"],
["自然","zìrán","nature; natural; naturally, of course"],["自习","zìxí","to study on one's own"],["自信","zìxìn","to believe in oneself; self-confidence, confidence; confident"],["自学","zìxué","to teach oneself, to self-study"],["总结","zǒngjié","to summarize, to sum up; summary"],
["租","zū","to rent, to hire"],["组","zǔ","group, team; (to organize; measure word for groups)"],["最终","zuìzhōng","final, ultimate"],["尊重","zūnzhòng","to respect, to value; respected"],["左右","zuǒyòu","about, around, left and right; (to control)"],
["座","zuò","seat, place; measure word for seats"],["做法","zuòfǎ","way of doing things, practice"],["作家","zuòjiā","writer, author"],["做梦","zuòmèng","to dream, to have a dream"],["作品","zuòpǐn","work, composition, creation"],
["作为","zuòwéi","to act as, to serve as; as, being"],["座位","zuòwèi","seat"],["作文","zuòwén","composition; to write a composition"],["作用","zuòyòng","function, role; (to serve as, to play a role)"],["作者","zuòzhě","author, writer"]
];
