#!/usr/bin/env node
// Generates chars.js — the character composition data behind the radical/component features.
//
//   node tools/build-chars.js
//
// Reads every hanzi used by the built-in word lists in data.js, looks each one up in Make Me a
// Hanzi's dictionary.txt, and writes out only that subset. dictionary.txt is ~2.5MB and covers
// all of Unicode, so it is downloaded to a temp file rather than committed — only the ~1,950
// characters this app actually teaches end up in the repo.
//
// Re-run this whenever data.js gains new words. It is deterministic (sorted by codepoint), so
// an unchanged word list produces a byte-identical chars.js.
//
// Source data is LGPL v3 — see NOTICE.md. Needs Node 18+ (for global fetch).

const fs = require('fs');
const os = require('os');
const path = require('path');

const REPO = path.resolve(__dirname, '..');
const DICT_URL = 'https://raw.githubusercontent.com/skishore/makemeahanzi/master/dictionary.txt';
const DICT_CACHE = path.join(os.tmpdir(), 'makemeahanzi-dictionary.txt');
const OUT = path.join(REPO, 'chars.js');

// the ⿰⿱⿲⿳⿴⿵⿶⿷⿸⿹⿺⿻ operators describe how pieces are arranged, they aren't pieces
// themselves; '？' is the source's marker for a piece it couldn't identify
const IDS_OPERATORS = /[⿰-⿿]/;
const UNKNOWN_PIECE = '？';
const isHanzi = (ch) => /[一-鿿]/.test(ch);
const piecesOf = (decomposition) =>
  decomposition ? Array.from(decomposition).filter((ch) => !IDS_OPERATORS.test(ch) && ch !== UNKNOWN_PIECE) : [];

async function loadDictionary(){
  if (!fs.existsSync(DICT_CACHE)) {
    process.stdout.write(`downloading dictionary.txt…\n`);
    const res = await fetch(DICT_URL);
    if (!res.ok) throw new Error(`could not fetch dictionary.txt: HTTP ${res.status}`);
    fs.writeFileSync(DICT_CACHE, Buffer.from(await res.arrayBuffer()));
  }
  const byChar = new Map();
  for (const line of fs.readFileSync(DICT_CACHE, 'utf8').split('\n')) {
    if (!line.trim()) continue;
    try {
      const entry = JSON.parse(line);
      byChar.set(entry.character, entry);
    } catch (e) { /* skip malformed lines rather than failing the whole build */ }
  }
  return byChar;
}

// data.js is a plain script of `const FULL_* = [...]` arrays, so evaluate it in a throwaway
// scope and hand the arrays back rather than duplicating the word lists here
function loadDeckCharacters(){
  const src = fs.readFileSync(path.join(REPO, 'data.js'), 'utf8').replace(/const /g, 'var ');
  const names = ['FULL_HSK1', 'FULL_HSK2', 'FULL_HSK3', 'FULL_HSK4', 'FULL_HSK5', 'FULL_HSK6', 'FULL_ES1', 'FULL_ES2'];
  const lists = new Function(`${src}; return {${names.join(',')}};`)();
  const chars = new Set();
  for (const list of Object.values(lists)) {
    for (const [word] of list) {
      for (const ch of Array.from(word)) if (isHanzi(ch)) chars.add(ch);
    }
  }
  return [...chars].sort((a, b) => a.codePointAt(0) - b.codePointAt(0));
}

const TYPE_CODES = { pictophonetic: 'p', ideographic: 'i', pictographic: 'g' };

// a handful of source hints carry a stray leading/trailing space or a doubled one mid-sentence
// ("Three  parallel lines"), which shows up verbatim in the app
const tidy = (text) => text.replace(/\s+/g, ' ').trim();

// Hand corrections, applied on top of the source. chars.js is generated, so fixes made by
// editing it directly would vanish on the next run — they live here instead. A field set to
// null is dropped, which is how a hint that can't be trusted gets removed without inventing a
// replacement for it.
function loadOverrides(){
  const file = path.join(__dirname, 'chars-overrides.json');
  if (!fs.existsSync(file)) return {};
  const raw = JSON.parse(fs.readFileSync(file, 'utf8'));
  delete raw.$comment;
  return raw;
}

function buildEntry(dictEntry, override){
  const out = {};
  if (dictEntry.decomposition) out.d = dictEntry.decomposition;
  if (dictEntry.radical) out.r = dictEntry.radical;
  const ety = dictEntry.etymology;
  if (ety) {
    if (TYPE_CODES[ety.type]) out.t = TYPE_CODES[ety.type];
    if (ety.semantic) out.s = ety.semantic;
    if (ety.phonetic) out.f = ety.phonetic;
    if (ety.hint) out.h = tidy(ety.hint);
  }
  Object.entries(override || {}).forEach(([field, value]) => {
    if (value === null) delete out[field]; else out[field] = typeof value === 'string' ? tidy(value) : value;
  });
  return out;
}

const HEADER = `// Character composition data for every hanzi used by the built-in word lists in data.js.
// GENERATED by tools/build-chars.js — do not hand-edit, re-run the script instead.
//
// Derived from Make Me a Hanzi's dictionary.txt, which is licensed LGPL v3 (see NOTICE.md and
// LICENSES/LGPL-3.0.txt). This file is kept separate from the app's own code so it stays
// replaceable, which is what the LGPL asks for.
//
// CHARS[character] = { d, r, t, s, f, h } — a field is omitted when the source has no value.
//   d  decomposition, as an Ideographic Description Sequence: "⿰女马" for 妈. The leading
//      ⿰⿱⿲⿳⿴⿵⿶⿷⿸⿹⿺⿻ symbol describes the layout and is not itself a component;
//      "？" marks a piece the source could not identify, so skip those when listing parts.
//   r  the character's Unicode radical.
//   t  how the character was formed — "p" pictophonetic (one part carries the meaning, another
//      the sound), "i" ideographic (the parts together suggest the meaning), "g" pictographic
//      (the character is a picture of the thing itself).
//   s  "p" only: the component carrying the meaning, e.g. 女 in 妈.
//   f  "p" only: the component carrying the sound, e.g. 马 in 妈.
//   h  a plain-English memory aid. This is mnemonic-grade, NOT scholarly etymology — the source
//      mixes in folk explanations and occasionally describes the simplified form rather than the
//      character's real history, so present it as a hint and never as a fact.
//
// COMPONENTS[piece] = [gloss, pinyin] for every piece referenced by a CHARS decomposition, so
// the parts can be labelled: 亻 reads as "man, person; people", 马 as "horse; surname" (mǎ).
// The pinyin matters most for the sound part of a pictophonetic character — that a 马 in 妈
// is there for its mǎ is the whole point, and most sound components aren't words the app
// teaches on their own, so their reading isn't available anywhere else. Either position can
// be an empty string when the source has no value for it.
`;

function serialise(name, obj){
  const lines = Object.entries(obj).map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`);
  return `const ${name} = {\n${lines.join('\n')}\n};\n`;
}

async function main(){
  const dict = await loadDictionary();
  const deckChars = loadDeckCharacters();
  const overrides = loadOverrides();

  const chars = {};
  const missing = [];
  for (const ch of deckChars) {
    const entry = dict.get(ch);
    if (!entry) { missing.push(ch); continue; }
    chars[ch] = buildEntry(entry, overrides[ch]);
  }

  // every piece referenced by a decomposition, so the UI can gloss the parts it shows
  const referenced = new Set();
  for (const [ch, entry] of Object.entries(chars)) {
    for (const piece of piecesOf(entry.d)) if (piece !== ch) referenced.add(piece);
  }
  const components = {};
  for (const piece of [...referenced].sort((a, b) => a.codePointAt(0) - b.codePointAt(0))) {
    const entry = dict.get(piece);
    if (!entry) continue;
    const gloss = entry.definition || '';
    const reading = (entry.pinyin && entry.pinyin[0]) || '';
    if (gloss || reading) components[piece] = [gloss, reading];
  }

  fs.writeFileSync(OUT, `${HEADER}${serialise('CHARS', chars)}\n${serialise('COMPONENTS', components)}`);

  const withParts = Object.values(chars).filter((c) => piecesOf(c.d).length >= 2).length;
  const withRoles = Object.values(chars).filter((c) => c.s && c.f).length;
  const withHint = Object.values(chars).filter((c) => c.h).length;
  console.log(`characters written : ${Object.keys(chars).length}`);
  console.log(`  with 2+ parts    : ${withParts}`);
  console.log(`  with sound+sense : ${withRoles}`);
  console.log(`  with a hint      : ${withHint}`);
  const glossed = Object.values(components).filter((c) => c[0]).length;
  const withReading = Object.values(components).filter((c) => c[1]).length;
  console.log(`components         : ${Object.keys(components).length} of ${referenced.size} referenced (${glossed} glossed, ${withReading} with pinyin)`);
  const applied = Object.keys(overrides).filter((ch) => chars[ch]).length;
  console.log(`hand corrections   : ${applied} applied of ${Object.keys(overrides).length} in chars-overrides.json`);
  if (missing.length) console.log(`not in dictionary  : ${missing.length} (${missing.join('')})`);
  console.log(`wrote ${path.relative(REPO, OUT)} (${(fs.statSync(OUT).size / 1024).toFixed(0)} KB)`);
}

main().catch((err) => { console.error(err); process.exit(1); });
